/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AddWhiteLabelConfig
 */
@JsonPropertyOrder({
  AddWhiteLabelConfig.JSON_PROPERTY_ORIGIN_ID,
  AddWhiteLabelConfig.JSON_PROPERTY_LOGO_URL,
  AddWhiteLabelConfig.JSON_PROPERTY_WEB_SITE_URL,
  AddWhiteLabelConfig.JSON_PROPERTY_SHOP_URL,
  AddWhiteLabelConfig.JSON_PROPERTY_SUPPORT_URL
})
public class AddWhiteLabelConfig {
  public static final String JSON_PROPERTY_ORIGIN_ID = "originId";
  private String originId;

  public static final String JSON_PROPERTY_LOGO_URL = "logoUrl";
  private String logoUrl;

  public static final String JSON_PROPERTY_WEB_SITE_URL = "webSiteUrl";
  private String webSiteUrl;

  public static final String JSON_PROPERTY_SHOP_URL = "shopUrl";
  private String shopUrl;

  public static final String JSON_PROPERTY_SUPPORT_URL = "supportUrl";
  private String supportUrl;

  public AddWhiteLabelConfig() {
  }

  public AddWhiteLabelConfig originId(String originId) {
    
    this.originId = originId;
    return this;
  }

   /**
   * Get originId
   * @return originId
  **/

  @JsonProperty(JSON_PROPERTY_ORIGIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOriginId() {
    return originId;
  }


  @JsonProperty(JSON_PROPERTY_ORIGIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOriginId(String originId) {
    this.originId = originId;
  }


  public AddWhiteLabelConfig logoUrl(String logoUrl) {
    
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/

  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoUrl() {
    return logoUrl;
  }


  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }


  public AddWhiteLabelConfig webSiteUrl(String webSiteUrl) {
    
    this.webSiteUrl = webSiteUrl;
    return this;
  }

   /**
   * Get webSiteUrl
   * @return webSiteUrl
  **/

  @JsonProperty(JSON_PROPERTY_WEB_SITE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebSiteUrl() {
    return webSiteUrl;
  }


  @JsonProperty(JSON_PROPERTY_WEB_SITE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebSiteUrl(String webSiteUrl) {
    this.webSiteUrl = webSiteUrl;
  }


  public AddWhiteLabelConfig shopUrl(String shopUrl) {
    
    this.shopUrl = shopUrl;
    return this;
  }

   /**
   * Get shopUrl
   * @return shopUrl
  **/

  @JsonProperty(JSON_PROPERTY_SHOP_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getShopUrl() {
    return shopUrl;
  }


  @JsonProperty(JSON_PROPERTY_SHOP_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShopUrl(String shopUrl) {
    this.shopUrl = shopUrl;
  }


  public AddWhiteLabelConfig supportUrl(String supportUrl) {
    
    this.supportUrl = supportUrl;
    return this;
  }

   /**
   * Get supportUrl
   * @return supportUrl
  **/

  @JsonProperty(JSON_PROPERTY_SUPPORT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSupportUrl() {
    return supportUrl;
  }


  @JsonProperty(JSON_PROPERTY_SUPPORT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupportUrl(String supportUrl) {
    this.supportUrl = supportUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddWhiteLabelConfig addWhiteLabelConfig = (AddWhiteLabelConfig) o;
    return Objects.equals(this.originId, addWhiteLabelConfig.originId) &&
        Objects.equals(this.logoUrl, addWhiteLabelConfig.logoUrl) &&
        Objects.equals(this.webSiteUrl, addWhiteLabelConfig.webSiteUrl) &&
        Objects.equals(this.shopUrl, addWhiteLabelConfig.shopUrl) &&
        Objects.equals(this.supportUrl, addWhiteLabelConfig.supportUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originId, logoUrl, webSiteUrl, shopUrl, supportUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddWhiteLabelConfig {\n");
    sb.append("    originId: ").append(toIndentedString(originId)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    webSiteUrl: ").append(toIndentedString(webSiteUrl)).append("\n");
    sb.append("    shopUrl: ").append(toIndentedString(shopUrl)).append("\n");
    sb.append("    supportUrl: ").append(toIndentedString(supportUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

