/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BaseCustomer
 */
@JsonPropertyOrder({
  BaseCustomer.JSON_PROPERTY_CUSTOMER_ID,
  BaseCustomer.JSON_PROPERTY_NAME,
  BaseCustomer.JSON_PROPERTY_ALLOW_SUB_CUSTOMERS,
  BaseCustomer.JSON_PROPERTY_ALLOW_DEVICE_GROUPS,
  BaseCustomer.JSON_PROPERTY_ALLOW_GATEWAY_GROUPS,
  BaseCustomer.JSON_PROPERTY_ALLOW_CUSTOMIZATIONS,
  BaseCustomer.JSON_PROPERTY_PARENT_ID,
  BaseCustomer.JSON_PROPERTY_SUB_CUSTOMERS
})
public class BaseCustomer {
  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private String customerId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ALLOW_SUB_CUSTOMERS = "allowSubCustomers";
  private Boolean allowSubCustomers;

  public static final String JSON_PROPERTY_ALLOW_DEVICE_GROUPS = "allowDeviceGroups";
  private Boolean allowDeviceGroups;

  public static final String JSON_PROPERTY_ALLOW_GATEWAY_GROUPS = "allowGatewayGroups";
  private Boolean allowGatewayGroups;

  public static final String JSON_PROPERTY_ALLOW_CUSTOMIZATIONS = "allowCustomizations";
  private Boolean allowCustomizations;

  public static final String JSON_PROPERTY_PARENT_ID = "parentId";
  private String parentId;

  public static final String JSON_PROPERTY_SUB_CUSTOMERS = "subCustomers";
  private List<BaseCustomer> subCustomers;

  public BaseCustomer() {
  }

  public BaseCustomer customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/

  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public BaseCustomer name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public BaseCustomer allowSubCustomers(Boolean allowSubCustomers) {
    
    this.allowSubCustomers = allowSubCustomers;
    return this;
  }

   /**
   * Get allowSubCustomers
   * @return allowSubCustomers
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_SUB_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAllowSubCustomers() {
    return allowSubCustomers;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_SUB_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowSubCustomers(Boolean allowSubCustomers) {
    this.allowSubCustomers = allowSubCustomers;
  }


  public BaseCustomer allowDeviceGroups(Boolean allowDeviceGroups) {
    
    this.allowDeviceGroups = allowDeviceGroups;
    return this;
  }

   /**
   * Get allowDeviceGroups
   * @return allowDeviceGroups
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_DEVICE_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAllowDeviceGroups() {
    return allowDeviceGroups;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_DEVICE_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowDeviceGroups(Boolean allowDeviceGroups) {
    this.allowDeviceGroups = allowDeviceGroups;
  }


  public BaseCustomer allowGatewayGroups(Boolean allowGatewayGroups) {
    
    this.allowGatewayGroups = allowGatewayGroups;
    return this;
  }

   /**
   * Get allowGatewayGroups
   * @return allowGatewayGroups
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_GATEWAY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAllowGatewayGroups() {
    return allowGatewayGroups;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_GATEWAY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowGatewayGroups(Boolean allowGatewayGroups) {
    this.allowGatewayGroups = allowGatewayGroups;
  }


  public BaseCustomer allowCustomizations(Boolean allowCustomizations) {
    
    this.allowCustomizations = allowCustomizations;
    return this;
  }

   /**
   * Get allowCustomizations
   * @return allowCustomizations
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_CUSTOMIZATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAllowCustomizations() {
    return allowCustomizations;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_CUSTOMIZATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAllowCustomizations(Boolean allowCustomizations) {
    this.allowCustomizations = allowCustomizations;
  }


  public BaseCustomer parentId(String parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/

  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentId() {
    return parentId;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  public BaseCustomer subCustomers(List<BaseCustomer> subCustomers) {
    
    this.subCustomers = subCustomers;
    return this;
  }

  public BaseCustomer addSubCustomersItem(BaseCustomer subCustomersItem) {
    if (this.subCustomers == null) {
      this.subCustomers = new ArrayList<>();
    }
    this.subCustomers.add(subCustomersItem);
    return this;
  }

   /**
   * Get subCustomers
   * @return subCustomers
  **/

  @JsonProperty(JSON_PROPERTY_SUB_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BaseCustomer> getSubCustomers() {
    return subCustomers;
  }


  @JsonProperty(JSON_PROPERTY_SUB_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubCustomers(List<BaseCustomer> subCustomers) {
    this.subCustomers = subCustomers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseCustomer baseCustomer = (BaseCustomer) o;
    return Objects.equals(this.customerId, baseCustomer.customerId) &&
        Objects.equals(this.name, baseCustomer.name) &&
        Objects.equals(this.allowSubCustomers, baseCustomer.allowSubCustomers) &&
        Objects.equals(this.allowDeviceGroups, baseCustomer.allowDeviceGroups) &&
        Objects.equals(this.allowGatewayGroups, baseCustomer.allowGatewayGroups) &&
        Objects.equals(this.allowCustomizations, baseCustomer.allowCustomizations) &&
        Objects.equals(this.parentId, baseCustomer.parentId) &&
        Objects.equals(this.subCustomers, baseCustomer.subCustomers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, name, allowSubCustomers, allowDeviceGroups, allowGatewayGroups, allowCustomizations, parentId, subCustomers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseCustomer {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    allowSubCustomers: ").append(toIndentedString(allowSubCustomers)).append("\n");
    sb.append("    allowDeviceGroups: ").append(toIndentedString(allowDeviceGroups)).append("\n");
    sb.append("    allowGatewayGroups: ").append(toIndentedString(allowGatewayGroups)).append("\n");
    sb.append("    allowCustomizations: ").append(toIndentedString(allowCustomizations)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    subCustomers: ").append(toIndentedString(subCustomers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

