/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CreateLoraDevice
 */
@JsonPropertyOrder({
  CreateLoraDevice.JSON_PROPERTY_DEV_EUI,
  CreateLoraDevice.JSON_PROPERTY_ACTIVE,
  CreateLoraDevice.JSON_PROPERTY_PROPERTY_CLASS,
  CreateLoraDevice.JSON_PROPERTY_LORA_VERSION,
  CreateLoraDevice.JSON_PROPERTY_CHANNEL_PLAN,
  CreateLoraDevice.JSON_PROPERTY_NETWORK_SERVER_ID,
  CreateLoraDevice.JSON_PROPERTY_PROVISIONED,
  CreateLoraDevice.JSON_PROPERTY_PROF_ID,
  CreateLoraDevice.JSON_PROPERTY_ACTIVATION_METHOD,
  CreateLoraDevice.JSON_PROPERTY_APP_EUI,
  CreateLoraDevice.JSON_PROPERTY_APP_KEY,
  CreateLoraDevice.JSON_PROPERTY_DEV_ADDR,
  CreateLoraDevice.JSON_PROPERTY_NWK_S_KEY,
  CreateLoraDevice.JSON_PROPERTY_APP_S_KEY,
  CreateLoraDevice.JSON_PROPERTY_NWK_KEY,
  CreateLoraDevice.JSON_PROPERTY_F_NWK_S_INT_KEY,
  CreateLoraDevice.JSON_PROPERTY_S_NWK_S_INT_KEY,
  CreateLoraDevice.JSON_PROPERTY_NWK_S_ENC_KEY
})
public class CreateLoraDevice {
  public static final String JSON_PROPERTY_DEV_EUI = "devEui";
  private String devEui;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_PROPERTY_CLASS = "class";
  private ModelClass propertyClass;

  public static final String JSON_PROPERTY_LORA_VERSION = "loraVersion";
  private LoraVersion loraVersion;

  public static final String JSON_PROPERTY_CHANNEL_PLAN = "channelPlan";
  private ChannelPlan channelPlan;

  public static final String JSON_PROPERTY_NETWORK_SERVER_ID = "networkServerId";
  private String networkServerId;

  public static final String JSON_PROPERTY_PROVISIONED = "provisioned";
  private Boolean provisioned;

  public static final String JSON_PROPERTY_PROF_ID = "profId";
  private Double profId;

  public static final String JSON_PROPERTY_ACTIVATION_METHOD = "activationMethod";
  private ActivationMethod activationMethod;

  public static final String JSON_PROPERTY_APP_EUI = "appEui";
  private String appEui;

  public static final String JSON_PROPERTY_APP_KEY = "appKey";
  private String appKey;

  public static final String JSON_PROPERTY_DEV_ADDR = "devAddr";
  private String devAddr;

  public static final String JSON_PROPERTY_NWK_S_KEY = "nwkSKey";
  private String nwkSKey;

  public static final String JSON_PROPERTY_APP_S_KEY = "appSKey";
  private String appSKey;

  public static final String JSON_PROPERTY_NWK_KEY = "nwkKey";
  private String nwkKey;

  public static final String JSON_PROPERTY_F_NWK_S_INT_KEY = "fNwkSIntKey";
  private String fNwkSIntKey;

  public static final String JSON_PROPERTY_S_NWK_S_INT_KEY = "sNwkSIntKey";
  private String sNwkSIntKey;

  public static final String JSON_PROPERTY_NWK_S_ENC_KEY = "nwkSEncKey";
  private String nwkSEncKey;

  public CreateLoraDevice() {
  }

  public CreateLoraDevice devEui(String devEui) {
    
    this.devEui = devEui;
    return this;
  }

   /**
   * *
   * @return devEui
  **/
  @JsonProperty(JSON_PROPERTY_DEV_EUI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDevEui() {
    return devEui;
  }


  @JsonProperty(JSON_PROPERTY_DEV_EUI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDevEui(String devEui) {
    this.devEui = devEui;
  }


  public CreateLoraDevice active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Default true
   * @return active
  **/

  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public CreateLoraDevice propertyClass(ModelClass propertyClass) {
    
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Get propertyClass
   * @return propertyClass
  **/

  @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ModelClass getPropertyClass() {
    return propertyClass;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPropertyClass(ModelClass propertyClass) {
    this.propertyClass = propertyClass;
  }


  public CreateLoraDevice loraVersion(LoraVersion loraVersion) {
    
    this.loraVersion = loraVersion;
    return this;
  }

   /**
   * Get loraVersion
   * @return loraVersion
  **/

  @JsonProperty(JSON_PROPERTY_LORA_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LoraVersion getLoraVersion() {
    return loraVersion;
  }


  @JsonProperty(JSON_PROPERTY_LORA_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLoraVersion(LoraVersion loraVersion) {
    this.loraVersion = loraVersion;
  }


  public CreateLoraDevice channelPlan(ChannelPlan channelPlan) {
    
    this.channelPlan = channelPlan;
    return this;
  }

   /**
   * Get channelPlan
   * @return channelPlan
  **/

  @JsonProperty(JSON_PROPERTY_CHANNEL_PLAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChannelPlan getChannelPlan() {
    return channelPlan;
  }


  @JsonProperty(JSON_PROPERTY_CHANNEL_PLAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChannelPlan(ChannelPlan channelPlan) {
    this.channelPlan = channelPlan;
  }


  public CreateLoraDevice networkServerId(String networkServerId) {
    
    this.networkServerId = networkServerId;
    return this;
  }

   /**
   * If not set use customer settings
   * @return networkServerId
  **/

  @JsonProperty(JSON_PROPERTY_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNetworkServerId() {
    return networkServerId;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetworkServerId(String networkServerId) {
    this.networkServerId = networkServerId;
  }


  public CreateLoraDevice provisioned(Boolean provisioned) {
    
    this.provisioned = provisioned;
    return this;
  }

   /**
   * Default false
   * @return provisioned
  **/

  @JsonProperty(JSON_PROPERTY_PROVISIONED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getProvisioned() {
    return provisioned;
  }


  @JsonProperty(JSON_PROPERTY_PROVISIONED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvisioned(Boolean provisioned) {
    this.provisioned = provisioned;
  }


  public CreateLoraDevice profId(Double profId) {
    
    this.profId = profId;
    return this;
  }

   /**
   * Get profId
   * @return profId
  **/

  @JsonProperty(JSON_PROPERTY_PROF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getProfId() {
    return profId;
  }


  @JsonProperty(JSON_PROPERTY_PROF_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfId(Double profId) {
    this.profId = profId;
  }


  public CreateLoraDevice activationMethod(ActivationMethod activationMethod) {
    
    this.activationMethod = activationMethod;
    return this;
  }

   /**
   * Get activationMethod
   * @return activationMethod
  **/

  @JsonProperty(JSON_PROPERTY_ACTIVATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActivationMethod getActivationMethod() {
    return activationMethod;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActivationMethod(ActivationMethod activationMethod) {
    this.activationMethod = activationMethod;
  }


  public CreateLoraDevice appEui(String appEui) {
    
    this.appEui = appEui;
    return this;
  }

   /**
   * *
   * @return appEui
  **/
  @JsonProperty(JSON_PROPERTY_APP_EUI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAppEui() {
    return appEui;
  }


  @JsonProperty(JSON_PROPERTY_APP_EUI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppEui(String appEui) {
    this.appEui = appEui;
  }


  public CreateLoraDevice appKey(String appKey) {
    
    this.appKey = appKey;
    return this;
  }

   /**
   * *
   * @return appKey
  **/
  @JsonProperty(JSON_PROPERTY_APP_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAppKey() {
    return appKey;
  }


  @JsonProperty(JSON_PROPERTY_APP_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppKey(String appKey) {
    this.appKey = appKey;
  }


  public CreateLoraDevice devAddr(String devAddr) {
    
    this.devAddr = devAddr;
    return this;
  }

   /**
   * *
   * @return devAddr
  **/
  @JsonProperty(JSON_PROPERTY_DEV_ADDR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDevAddr() {
    return devAddr;
  }


  @JsonProperty(JSON_PROPERTY_DEV_ADDR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDevAddr(String devAddr) {
    this.devAddr = devAddr;
  }


  public CreateLoraDevice nwkSKey(String nwkSKey) {
    
    this.nwkSKey = nwkSKey;
    return this;
  }

   /**
   * *
   * @return nwkSKey
  **/
  @JsonProperty(JSON_PROPERTY_NWK_S_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNwkSKey() {
    return nwkSKey;
  }


  @JsonProperty(JSON_PROPERTY_NWK_S_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNwkSKey(String nwkSKey) {
    this.nwkSKey = nwkSKey;
  }


  public CreateLoraDevice appSKey(String appSKey) {
    
    this.appSKey = appSKey;
    return this;
  }

   /**
   * *
   * @return appSKey
  **/
  @JsonProperty(JSON_PROPERTY_APP_S_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAppSKey() {
    return appSKey;
  }


  @JsonProperty(JSON_PROPERTY_APP_S_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppSKey(String appSKey) {
    this.appSKey = appSKey;
  }


  public CreateLoraDevice nwkKey(String nwkKey) {
    
    this.nwkKey = nwkKey;
    return this;
  }

   /**
   * *
   * @return nwkKey
  **/
  @JsonProperty(JSON_PROPERTY_NWK_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNwkKey() {
    return nwkKey;
  }


  @JsonProperty(JSON_PROPERTY_NWK_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNwkKey(String nwkKey) {
    this.nwkKey = nwkKey;
  }


  public CreateLoraDevice fNwkSIntKey(String fNwkSIntKey) {
    
    this.fNwkSIntKey = fNwkSIntKey;
    return this;
  }

   /**
   * *
   * @return fNwkSIntKey
  **/
  @JsonProperty(JSON_PROPERTY_F_NWK_S_INT_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getfNwkSIntKey() {
    return fNwkSIntKey;
  }


  @JsonProperty(JSON_PROPERTY_F_NWK_S_INT_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setfNwkSIntKey(String fNwkSIntKey) {
    this.fNwkSIntKey = fNwkSIntKey;
  }


  public CreateLoraDevice sNwkSIntKey(String sNwkSIntKey) {
    
    this.sNwkSIntKey = sNwkSIntKey;
    return this;
  }

   /**
   * *
   * @return sNwkSIntKey
  **/
  @JsonProperty(JSON_PROPERTY_S_NWK_S_INT_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getsNwkSIntKey() {
    return sNwkSIntKey;
  }


  @JsonProperty(JSON_PROPERTY_S_NWK_S_INT_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setsNwkSIntKey(String sNwkSIntKey) {
    this.sNwkSIntKey = sNwkSIntKey;
  }


  public CreateLoraDevice nwkSEncKey(String nwkSEncKey) {
    
    this.nwkSEncKey = nwkSEncKey;
    return this;
  }

   /**
   * *
   * @return nwkSEncKey
  **/
  @JsonProperty(JSON_PROPERTY_NWK_S_ENC_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNwkSEncKey() {
    return nwkSEncKey;
  }


  @JsonProperty(JSON_PROPERTY_NWK_S_ENC_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNwkSEncKey(String nwkSEncKey) {
    this.nwkSEncKey = nwkSEncKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLoraDevice createLoraDevice = (CreateLoraDevice) o;
    return Objects.equals(this.devEui, createLoraDevice.devEui) &&
        Objects.equals(this.active, createLoraDevice.active) &&
        Objects.equals(this.propertyClass, createLoraDevice.propertyClass) &&
        Objects.equals(this.loraVersion, createLoraDevice.loraVersion) &&
        Objects.equals(this.channelPlan, createLoraDevice.channelPlan) &&
        Objects.equals(this.networkServerId, createLoraDevice.networkServerId) &&
        Objects.equals(this.provisioned, createLoraDevice.provisioned) &&
        Objects.equals(this.profId, createLoraDevice.profId) &&
        Objects.equals(this.activationMethod, createLoraDevice.activationMethod) &&
        Objects.equals(this.appEui, createLoraDevice.appEui) &&
        Objects.equals(this.appKey, createLoraDevice.appKey) &&
        Objects.equals(this.devAddr, createLoraDevice.devAddr) &&
        Objects.equals(this.nwkSKey, createLoraDevice.nwkSKey) &&
        Objects.equals(this.appSKey, createLoraDevice.appSKey) &&
        Objects.equals(this.nwkKey, createLoraDevice.nwkKey) &&
        Objects.equals(this.fNwkSIntKey, createLoraDevice.fNwkSIntKey) &&
        Objects.equals(this.sNwkSIntKey, createLoraDevice.sNwkSIntKey) &&
        Objects.equals(this.nwkSEncKey, createLoraDevice.nwkSEncKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(devEui, active, propertyClass, loraVersion, channelPlan, networkServerId, provisioned, profId, activationMethod, appEui, appKey, devAddr, nwkSKey, appSKey, nwkKey, fNwkSIntKey, sNwkSIntKey, nwkSEncKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLoraDevice {\n");
    sb.append("    devEui: ").append(toIndentedString(devEui)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    loraVersion: ").append(toIndentedString(loraVersion)).append("\n");
    sb.append("    channelPlan: ").append(toIndentedString(channelPlan)).append("\n");
    sb.append("    networkServerId: ").append(toIndentedString(networkServerId)).append("\n");
    sb.append("    provisioned: ").append(toIndentedString(provisioned)).append("\n");
    sb.append("    profId: ").append(toIndentedString(profId)).append("\n");
    sb.append("    activationMethod: ").append(toIndentedString(activationMethod)).append("\n");
    sb.append("    appEui: ").append(toIndentedString(appEui)).append("\n");
    sb.append("    appKey: ").append(toIndentedString(appKey)).append("\n");
    sb.append("    devAddr: ").append(toIndentedString(devAddr)).append("\n");
    sb.append("    nwkSKey: ").append(toIndentedString(nwkSKey)).append("\n");
    sb.append("    appSKey: ").append(toIndentedString(appSKey)).append("\n");
    sb.append("    nwkKey: ").append(toIndentedString(nwkKey)).append("\n");
    sb.append("    fNwkSIntKey: ").append(toIndentedString(fNwkSIntKey)).append("\n");
    sb.append("    sNwkSIntKey: ").append(toIndentedString(sNwkSIntKey)).append("\n");
    sb.append("    nwkSEncKey: ").append(toIndentedString(nwkSEncKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

