/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import lora.ns.netmore.rest.model.UserRights;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateUserRequest
 */
@JsonPropertyOrder({
  CreateUserRequest.JSON_PROPERTY_USERNAME,
  CreateUserRequest.JSON_PROPERTY_FIRST_NAME,
  CreateUserRequest.JSON_PROPERTY_LAST_NAME,
  CreateUserRequest.JSON_PROPERTY_EMAIL,
  CreateUserRequest.JSON_PROPERTY_PHONE_NUMBER,
  CreateUserRequest.JSON_PROPERTY_RIGHTS,
  CreateUserRequest.JSON_PROPERTY_ENABLED,
  CreateUserRequest.JSON_PROPERTY_PASSWORD,
  CreateUserRequest.JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES,
  CreateUserRequest.JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES,
  CreateUserRequest.JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES,
  CreateUserRequest.JSON_PROPERTY_MAP_CENTER_LATITUDE,
  CreateUserRequest.JSON_PROPERTY_MAP_CENTER_LONGITUDE,
  CreateUserRequest.JSON_PROPERTY_MAP_ZOOM_LEVEL,
  CreateUserRequest.JSON_PROPERTY_CLIENT_ID,
  CreateUserRequest.JSON_PROPERTY_TOTP
})
public class CreateUserRequest {
  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  private String phoneNumber;

  public static final String JSON_PROPERTY_RIGHTS = "rights";
  private List<UserRights> rights = new ArrayList<>();

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES = "mailNotificationsDisturbances";
  private Boolean mailNotificationsDisturbances;

  public static final String JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES = "mailNotificationsReleaseNotes";
  private Boolean mailNotificationsReleaseNotes;

  public static final String JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES = "mailNotificationsUpcomingReleases";
  private Boolean mailNotificationsUpcomingReleases;

  public static final String JSON_PROPERTY_MAP_CENTER_LATITUDE = "mapCenterLatitude";
  private Double mapCenterLatitude;

  public static final String JSON_PROPERTY_MAP_CENTER_LONGITUDE = "mapCenterLongitude";
  private Double mapCenterLongitude;

  public static final String JSON_PROPERTY_MAP_ZOOM_LEVEL = "mapZoomLevel";
  private Double mapZoomLevel;

  public static final String JSON_PROPERTY_CLIENT_ID = "clientId";
  private String clientId;

  public static final String JSON_PROPERTY_TOTP = "totp";
  private Boolean totp;

  public CreateUserRequest() {
  }

  public CreateUserRequest username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/

  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(String username) {
    this.username = username;
  }


  public CreateUserRequest firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/

  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public CreateUserRequest lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/

  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public CreateUserRequest email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/

  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(String email) {
    this.email = email;
  }


  public CreateUserRequest phoneNumber(String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/

  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public CreateUserRequest rights(List<UserRights> rights) {
    
    this.rights = rights;
    return this;
  }

  public CreateUserRequest addRightsItem(UserRights rightsItem) {
    if (this.rights == null) {
      this.rights = new ArrayList<>();
    }
    this.rights.add(rightsItem);
    return this;
  }

   /**
   * Get rights
   * @return rights
  **/

  @JsonProperty(JSON_PROPERTY_RIGHTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<UserRights> getRights() {
    return rights;
  }


  @JsonProperty(JSON_PROPERTY_RIGHTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRights(List<UserRights> rights) {
    this.rights = rights;
  }


  public CreateUserRequest enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/

  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public CreateUserRequest password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
   * @deprecated
  **/
  @Deprecated

  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(String password) {
    this.password = password;
  }


  public CreateUserRequest mailNotificationsDisturbances(Boolean mailNotificationsDisturbances) {
    
    this.mailNotificationsDisturbances = mailNotificationsDisturbances;
    return this;
  }

   /**
   * Get mailNotificationsDisturbances
   * @return mailNotificationsDisturbances
  **/

  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailNotificationsDisturbances() {
    return mailNotificationsDisturbances;
  }


  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailNotificationsDisturbances(Boolean mailNotificationsDisturbances) {
    this.mailNotificationsDisturbances = mailNotificationsDisturbances;
  }


  public CreateUserRequest mailNotificationsReleaseNotes(Boolean mailNotificationsReleaseNotes) {
    
    this.mailNotificationsReleaseNotes = mailNotificationsReleaseNotes;
    return this;
  }

   /**
   * Get mailNotificationsReleaseNotes
   * @return mailNotificationsReleaseNotes
  **/

  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailNotificationsReleaseNotes() {
    return mailNotificationsReleaseNotes;
  }


  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailNotificationsReleaseNotes(Boolean mailNotificationsReleaseNotes) {
    this.mailNotificationsReleaseNotes = mailNotificationsReleaseNotes;
  }


  public CreateUserRequest mailNotificationsUpcomingReleases(Boolean mailNotificationsUpcomingReleases) {
    
    this.mailNotificationsUpcomingReleases = mailNotificationsUpcomingReleases;
    return this;
  }

   /**
   * Get mailNotificationsUpcomingReleases
   * @return mailNotificationsUpcomingReleases
  **/

  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailNotificationsUpcomingReleases() {
    return mailNotificationsUpcomingReleases;
  }


  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailNotificationsUpcomingReleases(Boolean mailNotificationsUpcomingReleases) {
    this.mailNotificationsUpcomingReleases = mailNotificationsUpcomingReleases;
  }


  public CreateUserRequest mapCenterLatitude(Double mapCenterLatitude) {
    
    this.mapCenterLatitude = mapCenterLatitude;
    return this;
  }

   /**
   * Get mapCenterLatitude
   * @return mapCenterLatitude
  **/

  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMapCenterLatitude() {
    return mapCenterLatitude;
  }


  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapCenterLatitude(Double mapCenterLatitude) {
    this.mapCenterLatitude = mapCenterLatitude;
  }


  public CreateUserRequest mapCenterLongitude(Double mapCenterLongitude) {
    
    this.mapCenterLongitude = mapCenterLongitude;
    return this;
  }

   /**
   * Get mapCenterLongitude
   * @return mapCenterLongitude
  **/

  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMapCenterLongitude() {
    return mapCenterLongitude;
  }


  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapCenterLongitude(Double mapCenterLongitude) {
    this.mapCenterLongitude = mapCenterLongitude;
  }


  public CreateUserRequest mapZoomLevel(Double mapZoomLevel) {
    
    this.mapZoomLevel = mapZoomLevel;
    return this;
  }

   /**
   * Get mapZoomLevel
   * @return mapZoomLevel
  **/

  @JsonProperty(JSON_PROPERTY_MAP_ZOOM_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMapZoomLevel() {
    return mapZoomLevel;
  }


  @JsonProperty(JSON_PROPERTY_MAP_ZOOM_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapZoomLevel(Double mapZoomLevel) {
    this.mapZoomLevel = mapZoomLevel;
  }


  public CreateUserRequest clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/

  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientId() {
    return clientId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public CreateUserRequest totp(Boolean totp) {
    
    this.totp = totp;
    return this;
  }

   /**
   * Might be overwrite by customer policy
   * @return totp
  **/

  @JsonProperty(JSON_PROPERTY_TOTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTotp() {
    return totp;
  }


  @JsonProperty(JSON_PROPERTY_TOTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotp(Boolean totp) {
    this.totp = totp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateUserRequest createUserRequest = (CreateUserRequest) o;
    return Objects.equals(this.username, createUserRequest.username) &&
        Objects.equals(this.firstName, createUserRequest.firstName) &&
        Objects.equals(this.lastName, createUserRequest.lastName) &&
        Objects.equals(this.email, createUserRequest.email) &&
        Objects.equals(this.phoneNumber, createUserRequest.phoneNumber) &&
        Objects.equals(this.rights, createUserRequest.rights) &&
        Objects.equals(this.enabled, createUserRequest.enabled) &&
        Objects.equals(this.password, createUserRequest.password) &&
        Objects.equals(this.mailNotificationsDisturbances, createUserRequest.mailNotificationsDisturbances) &&
        Objects.equals(this.mailNotificationsReleaseNotes, createUserRequest.mailNotificationsReleaseNotes) &&
        Objects.equals(this.mailNotificationsUpcomingReleases, createUserRequest.mailNotificationsUpcomingReleases) &&
        Objects.equals(this.mapCenterLatitude, createUserRequest.mapCenterLatitude) &&
        Objects.equals(this.mapCenterLongitude, createUserRequest.mapCenterLongitude) &&
        Objects.equals(this.mapZoomLevel, createUserRequest.mapZoomLevel) &&
        Objects.equals(this.clientId, createUserRequest.clientId) &&
        Objects.equals(this.totp, createUserRequest.totp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, firstName, lastName, email, phoneNumber, rights, enabled, password, mailNotificationsDisturbances, mailNotificationsReleaseNotes, mailNotificationsUpcomingReleases, mapCenterLatitude, mapCenterLongitude, mapZoomLevel, clientId, totp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateUserRequest {\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    rights: ").append(toIndentedString(rights)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    mailNotificationsDisturbances: ").append(toIndentedString(mailNotificationsDisturbances)).append("\n");
    sb.append("    mailNotificationsReleaseNotes: ").append(toIndentedString(mailNotificationsReleaseNotes)).append("\n");
    sb.append("    mailNotificationsUpcomingReleases: ").append(toIndentedString(mailNotificationsUpcomingReleases)).append("\n");
    sb.append("    mapCenterLatitude: ").append(toIndentedString(mapCenterLatitude)).append("\n");
    sb.append("    mapCenterLongitude: ").append(toIndentedString(mapCenterLongitude)).append("\n");
    sb.append("    mapZoomLevel: ").append(toIndentedString(mapZoomLevel)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    totp: ").append(toIndentedString(totp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

