/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lora.ns.netmore.rest.model.CustomerAddRequestDevices;
import lora.ns.netmore.rest.model.CustomerAddRequestGateways;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CustomerAddRequest
 */
@JsonPropertyOrder({
  CustomerAddRequest.JSON_PROPERTY_NAME,
  CustomerAddRequest.JSON_PROPERTY_ALLOW_SUB_CUSTOMERS,
  CustomerAddRequest.JSON_PROPERTY_ALLOW_DEVICE_GROUPS,
  CustomerAddRequest.JSON_PROPERTY_ALLOW_GATEWAY_GROUPS,
  CustomerAddRequest.JSON_PROPERTY_ALLOW_CUSTOMIZATIONS,
  CustomerAddRequest.JSON_PROPERTY_EXTERNAL_REFERENCE,
  CustomerAddRequest.JSON_PROPERTY_REQUIRE_T_OTP,
  CustomerAddRequest.JSON_PROPERTY_TAGS,
  CustomerAddRequest.JSON_PROPERTY_OPERATOR,
  CustomerAddRequest.JSON_PROPERTY_GATEWAYS,
  CustomerAddRequest.JSON_PROPERTY_DEVICES
})
public class CustomerAddRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ALLOW_SUB_CUSTOMERS = "allowSubCustomers";
  private Boolean allowSubCustomers;

  public static final String JSON_PROPERTY_ALLOW_DEVICE_GROUPS = "allowDeviceGroups";
  private Boolean allowDeviceGroups;

  public static final String JSON_PROPERTY_ALLOW_GATEWAY_GROUPS = "allowGatewayGroups";
  private Boolean allowGatewayGroups;

  public static final String JSON_PROPERTY_ALLOW_CUSTOMIZATIONS = "allowCustomizations";
  private Boolean allowCustomizations;

  public static final String JSON_PROPERTY_EXTERNAL_REFERENCE = "externalReference";
  private String externalReference;

  public static final String JSON_PROPERTY_REQUIRE_T_OTP = "requireTOtp";
  private Boolean requireTOtp;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private Map<String, List<String>> tags = new HashMap<>();

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  private Boolean operator;

  public static final String JSON_PROPERTY_GATEWAYS = "gateways";
  private CustomerAddRequestGateways gateways;

  public static final String JSON_PROPERTY_DEVICES = "devices";
  private CustomerAddRequestDevices devices;

  public CustomerAddRequest() {
  }

  public CustomerAddRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the customer
   * @return name
  **/
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public CustomerAddRequest allowSubCustomers(Boolean allowSubCustomers) {
    
    this.allowSubCustomers = allowSubCustomers;
    return this;
  }

   /**
   * Allow creation of sub customers default is false
   * @return allowSubCustomers
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_SUB_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowSubCustomers() {
    return allowSubCustomers;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_SUB_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowSubCustomers(Boolean allowSubCustomers) {
    this.allowSubCustomers = allowSubCustomers;
  }


  public CustomerAddRequest allowDeviceGroups(Boolean allowDeviceGroups) {
    
    this.allowDeviceGroups = allowDeviceGroups;
    return this;
  }

   /**
   * Allow creation of device groups default is false
   * @return allowDeviceGroups
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_DEVICE_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowDeviceGroups() {
    return allowDeviceGroups;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_DEVICE_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowDeviceGroups(Boolean allowDeviceGroups) {
    this.allowDeviceGroups = allowDeviceGroups;
  }


  public CustomerAddRequest allowGatewayGroups(Boolean allowGatewayGroups) {
    
    this.allowGatewayGroups = allowGatewayGroups;
    return this;
  }

   /**
   * Allow creation of gateway groups default is true
   * @return allowGatewayGroups
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_GATEWAY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowGatewayGroups() {
    return allowGatewayGroups;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_GATEWAY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowGatewayGroups(Boolean allowGatewayGroups) {
    this.allowGatewayGroups = allowGatewayGroups;
  }


  public CustomerAddRequest allowCustomizations(Boolean allowCustomizations) {
    
    this.allowCustomizations = allowCustomizations;
    return this;
  }

   /**
   * Allow customer white labeling etc default is false
   * @return allowCustomizations
  **/

  @JsonProperty(JSON_PROPERTY_ALLOW_CUSTOMIZATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllowCustomizations() {
    return allowCustomizations;
  }


  @JsonProperty(JSON_PROPERTY_ALLOW_CUSTOMIZATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowCustomizations(Boolean allowCustomizations) {
    this.allowCustomizations = allowCustomizations;
  }


  public CustomerAddRequest externalReference(String externalReference) {
    
    this.externalReference = externalReference;
    return this;
  }

   /**
   * External reference ex: billing reference
   * @return externalReference
  **/

  @JsonProperty(JSON_PROPERTY_EXTERNAL_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalReference() {
    return externalReference;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_REFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }


  public CustomerAddRequest requireTOtp(Boolean requireTOtp) {
    
    this.requireTOtp = requireTOtp;
    return this;
  }

   /**
   * Require TOTP for all users
   * @return requireTOtp
  **/

  @JsonProperty(JSON_PROPERTY_REQUIRE_T_OTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRequireTOtp() {
    return requireTOtp;
  }


  @JsonProperty(JSON_PROPERTY_REQUIRE_T_OTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequireTOtp(Boolean requireTOtp) {
    this.requireTOtp = requireTOtp;
  }


  public CustomerAddRequest tags(Map<String, List<String>> tags) {
    
    this.tags = tags;
    return this;
  }

  public CustomerAddRequest putTagsItem(String key, List<String> tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<String>> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(Map<String, List<String>> tags) {
    this.tags = tags;
  }


  public CustomerAddRequest operator(Boolean operator) {
    
    this.operator = operator;
    return this;
  }

   /**
   * Only global admin can set this, for everyone else this will be filtered out.
   * @return operator
  **/

  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperator(Boolean operator) {
    this.operator = operator;
  }


  public CustomerAddRequest gateways(CustomerAddRequestGateways gateways) {
    
    this.gateways = gateways;
    return this;
  }

   /**
   * Get gateways
   * @return gateways
  **/

  @JsonProperty(JSON_PROPERTY_GATEWAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerAddRequestGateways getGateways() {
    return gateways;
  }


  @JsonProperty(JSON_PROPERTY_GATEWAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGateways(CustomerAddRequestGateways gateways) {
    this.gateways = gateways;
  }


  public CustomerAddRequest devices(CustomerAddRequestDevices devices) {
    
    this.devices = devices;
    return this;
  }

   /**
   * Get devices
   * @return devices
  **/

  @JsonProperty(JSON_PROPERTY_DEVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerAddRequestDevices getDevices() {
    return devices;
  }


  @JsonProperty(JSON_PROPERTY_DEVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevices(CustomerAddRequestDevices devices) {
    this.devices = devices;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerAddRequest customerAddRequest = (CustomerAddRequest) o;
    return Objects.equals(this.name, customerAddRequest.name) &&
        Objects.equals(this.allowSubCustomers, customerAddRequest.allowSubCustomers) &&
        Objects.equals(this.allowDeviceGroups, customerAddRequest.allowDeviceGroups) &&
        Objects.equals(this.allowGatewayGroups, customerAddRequest.allowGatewayGroups) &&
        Objects.equals(this.allowCustomizations, customerAddRequest.allowCustomizations) &&
        Objects.equals(this.externalReference, customerAddRequest.externalReference) &&
        Objects.equals(this.requireTOtp, customerAddRequest.requireTOtp) &&
        Objects.equals(this.tags, customerAddRequest.tags) &&
        Objects.equals(this.operator, customerAddRequest.operator) &&
        Objects.equals(this.gateways, customerAddRequest.gateways) &&
        Objects.equals(this.devices, customerAddRequest.devices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, allowSubCustomers, allowDeviceGroups, allowGatewayGroups, allowCustomizations, externalReference, requireTOtp, tags, operator, gateways, devices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerAddRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    allowSubCustomers: ").append(toIndentedString(allowSubCustomers)).append("\n");
    sb.append("    allowDeviceGroups: ").append(toIndentedString(allowDeviceGroups)).append("\n");
    sb.append("    allowGatewayGroups: ").append(toIndentedString(allowGatewayGroups)).append("\n");
    sb.append("    allowCustomizations: ").append(toIndentedString(allowCustomizations)).append("\n");
    sb.append("    externalReference: ").append(toIndentedString(externalReference)).append("\n");
    sb.append("    requireTOtp: ").append(toIndentedString(requireTOtp)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    gateways: ").append(toIndentedString(gateways)).append("\n");
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

