/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import lora.ns.netmore.rest.model.CustomerOperatorUpdateRequestDevices;
import lora.ns.netmore.rest.model.CustomerOperatorUpdateRequestGateways;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CustomerOperatorUpdateRequest
 */
@JsonPropertyOrder({
  CustomerOperatorUpdateRequest.JSON_PROPERTY_OPERATOR,
  CustomerOperatorUpdateRequest.JSON_PROPERTY_VALID_NETWORK_SERVERS,
  CustomerOperatorUpdateRequest.JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID,
  CustomerOperatorUpdateRequest.JSON_PROPERTY_DEVICES,
  CustomerOperatorUpdateRequest.JSON_PROPERTY_GATEWAYS
})
public class CustomerOperatorUpdateRequest {
  public static final String JSON_PROPERTY_OPERATOR = "operator";
  private Boolean operator;

  public static final String JSON_PROPERTY_VALID_NETWORK_SERVERS = "validNetworkServers";
  private List<String> validNetworkServers;

  public static final String JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID = "defaultNetworkServerId";
  private String defaultNetworkServerId;

  public static final String JSON_PROPERTY_DEVICES = "devices";
  private CustomerOperatorUpdateRequestDevices devices;

  public static final String JSON_PROPERTY_GATEWAYS = "gateways";
  private CustomerOperatorUpdateRequestGateways gateways;

  public CustomerOperatorUpdateRequest() {
  }

  public CustomerOperatorUpdateRequest operator(Boolean operator) {
    
    this.operator = operator;
    return this;
  }

   /**
   * This can not be edited by other then global admin
   * @return operator
  **/

  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperator(Boolean operator) {
    this.operator = operator;
  }


  public CustomerOperatorUpdateRequest validNetworkServers(List<String> validNetworkServers) {
    
    this.validNetworkServers = validNetworkServers;
    return this;
  }

  public CustomerOperatorUpdateRequest addValidNetworkServersItem(String validNetworkServersItem) {
    if (this.validNetworkServers == null) {
      this.validNetworkServers = new ArrayList<>();
    }
    this.validNetworkServers.add(validNetworkServersItem);
    return this;
  }

   /**
   * Get validNetworkServers
   * @return validNetworkServers
  **/

  @JsonProperty(JSON_PROPERTY_VALID_NETWORK_SERVERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getValidNetworkServers() {
    return validNetworkServers;
  }


  @JsonProperty(JSON_PROPERTY_VALID_NETWORK_SERVERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidNetworkServers(List<String> validNetworkServers) {
    this.validNetworkServers = validNetworkServers;
  }


  public CustomerOperatorUpdateRequest defaultNetworkServerId(String defaultNetworkServerId) {
    
    this.defaultNetworkServerId = defaultNetworkServerId;
    return this;
  }

   /**
   * Get defaultNetworkServerId
   * @return defaultNetworkServerId
  **/

  @JsonProperty(JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultNetworkServerId() {
    return defaultNetworkServerId;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultNetworkServerId(String defaultNetworkServerId) {
    this.defaultNetworkServerId = defaultNetworkServerId;
  }


  public CustomerOperatorUpdateRequest devices(CustomerOperatorUpdateRequestDevices devices) {
    
    this.devices = devices;
    return this;
  }

   /**
   * Get devices
   * @return devices
  **/

  @JsonProperty(JSON_PROPERTY_DEVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerOperatorUpdateRequestDevices getDevices() {
    return devices;
  }


  @JsonProperty(JSON_PROPERTY_DEVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevices(CustomerOperatorUpdateRequestDevices devices) {
    this.devices = devices;
  }


  public CustomerOperatorUpdateRequest gateways(CustomerOperatorUpdateRequestGateways gateways) {
    
    this.gateways = gateways;
    return this;
  }

   /**
   * Get gateways
   * @return gateways
  **/

  @JsonProperty(JSON_PROPERTY_GATEWAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerOperatorUpdateRequestGateways getGateways() {
    return gateways;
  }


  @JsonProperty(JSON_PROPERTY_GATEWAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGateways(CustomerOperatorUpdateRequestGateways gateways) {
    this.gateways = gateways;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerOperatorUpdateRequest customerOperatorUpdateRequest = (CustomerOperatorUpdateRequest) o;
    return Objects.equals(this.operator, customerOperatorUpdateRequest.operator) &&
        Objects.equals(this.validNetworkServers, customerOperatorUpdateRequest.validNetworkServers) &&
        Objects.equals(this.defaultNetworkServerId, customerOperatorUpdateRequest.defaultNetworkServerId) &&
        Objects.equals(this.devices, customerOperatorUpdateRequest.devices) &&
        Objects.equals(this.gateways, customerOperatorUpdateRequest.gateways);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operator, validNetworkServers, defaultNetworkServerId, devices, gateways);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerOperatorUpdateRequest {\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    validNetworkServers: ").append(toIndentedString(validNetworkServers)).append("\n");
    sb.append("    defaultNetworkServerId: ").append(toIndentedString(defaultNetworkServerId)).append("\n");
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("    gateways: ").append(toIndentedString(gateways)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

