/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import lora.ns.netmore.rest.model.ChannelPlan;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * devices need to be set if the customer is allowDeviceGroups&#x3D;true. if its not all data will be copied from parent.
 */
@JsonPropertyOrder({
  CustomerAddRequestDevices.JSON_PROPERTY_VALID_PRODUCTS,
  CustomerAddRequestDevices.JSON_PROPERTY_DEFAULT_PRODUCT_ID,
  CustomerAddRequestDevices.JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID,
  CustomerAddRequestDevices.JSON_PROPERTY_VALID_NETWORK_SERVERS,
  CustomerAddRequestDevices.JSON_PROPERTY_DEFAULT_CHANNEL_PLAN_ID
})
@JsonTypeName("CustomerAddRequest_devices")
public class CustomerAddRequestDevices {
  public static final String JSON_PROPERTY_VALID_PRODUCTS = "validProducts";
  private List<String> validProducts;

  public static final String JSON_PROPERTY_DEFAULT_PRODUCT_ID = "defaultProductId";
  private String defaultProductId;

  public static final String JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID = "defaultNetworkServerId";
  private String defaultNetworkServerId;

  public static final String JSON_PROPERTY_VALID_NETWORK_SERVERS = "validNetworkServers";
  private List<String> validNetworkServers;

  public static final String JSON_PROPERTY_DEFAULT_CHANNEL_PLAN_ID = "defaultChannelPlanId";
  private ChannelPlan defaultChannelPlanId;

  public CustomerAddRequestDevices() {
  }

  public CustomerAddRequestDevices validProducts(List<String> validProducts) {
    
    this.validProducts = validProducts;
    return this;
  }

  public CustomerAddRequestDevices addValidProductsItem(String validProductsItem) {
    if (this.validProducts == null) {
      this.validProducts = new ArrayList<>();
    }
    this.validProducts.add(validProductsItem);
    return this;
  }

   /**
   * List of all ids for valid products, if not set will be copied from parent
   * @return validProducts
  **/

  @JsonProperty(JSON_PROPERTY_VALID_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getValidProducts() {
    return validProducts;
  }


  @JsonProperty(JSON_PROPERTY_VALID_PRODUCTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidProducts(List<String> validProducts) {
    this.validProducts = validProducts;
  }


  public CustomerAddRequestDevices defaultProductId(String defaultProductId) {
    
    this.defaultProductId = defaultProductId;
    return this;
  }

   /**
   * Default product, if not set will be copied from parent
   * @return defaultProductId
  **/

  @JsonProperty(JSON_PROPERTY_DEFAULT_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultProductId() {
    return defaultProductId;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultProductId(String defaultProductId) {
    this.defaultProductId = defaultProductId;
  }


  public CustomerAddRequestDevices defaultNetworkServerId(String defaultNetworkServerId) {
    
    this.defaultNetworkServerId = defaultNetworkServerId;
    return this;
  }

   /**
   * Default network server, if not set will be copied from parent
   * @return defaultNetworkServerId
  **/

  @JsonProperty(JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDefaultNetworkServerId() {
    return defaultNetworkServerId;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultNetworkServerId(String defaultNetworkServerId) {
    this.defaultNetworkServerId = defaultNetworkServerId;
  }


  public CustomerAddRequestDevices validNetworkServers(List<String> validNetworkServers) {
    
    this.validNetworkServers = validNetworkServers;
    return this;
  }

  public CustomerAddRequestDevices addValidNetworkServersItem(String validNetworkServersItem) {
    if (this.validNetworkServers == null) {
      this.validNetworkServers = new ArrayList<>();
    }
    this.validNetworkServers.add(validNetworkServersItem);
    return this;
  }

   /**
   * List of ids for all valid network servers, if not set will be copied from parent
   * @return validNetworkServers
  **/

  @JsonProperty(JSON_PROPERTY_VALID_NETWORK_SERVERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getValidNetworkServers() {
    return validNetworkServers;
  }


  @JsonProperty(JSON_PROPERTY_VALID_NETWORK_SERVERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidNetworkServers(List<String> validNetworkServers) {
    this.validNetworkServers = validNetworkServers;
  }


  public CustomerAddRequestDevices defaultChannelPlanId(ChannelPlan defaultChannelPlanId) {
    
    this.defaultChannelPlanId = defaultChannelPlanId;
    return this;
  }

   /**
   * Get defaultChannelPlanId
   * @return defaultChannelPlanId
  **/

  @JsonProperty(JSON_PROPERTY_DEFAULT_CHANNEL_PLAN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChannelPlan getDefaultChannelPlanId() {
    return defaultChannelPlanId;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_CHANNEL_PLAN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultChannelPlanId(ChannelPlan defaultChannelPlanId) {
    this.defaultChannelPlanId = defaultChannelPlanId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerAddRequestDevices customerAddRequestDevices = (CustomerAddRequestDevices) o;
    return Objects.equals(this.validProducts, customerAddRequestDevices.validProducts) &&
        Objects.equals(this.defaultProductId, customerAddRequestDevices.defaultProductId) &&
        Objects.equals(this.defaultNetworkServerId, customerAddRequestDevices.defaultNetworkServerId) &&
        Objects.equals(this.validNetworkServers, customerAddRequestDevices.validNetworkServers) &&
        Objects.equals(this.defaultChannelPlanId, customerAddRequestDevices.defaultChannelPlanId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validProducts, defaultProductId, defaultNetworkServerId, validNetworkServers, defaultChannelPlanId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerAddRequestDevices {\n");
    sb.append("    validProducts: ").append(toIndentedString(validProducts)).append("\n");
    sb.append("    defaultProductId: ").append(toIndentedString(defaultProductId)).append("\n");
    sb.append("    defaultNetworkServerId: ").append(toIndentedString(defaultNetworkServerId)).append("\n");
    sb.append("    validNetworkServers: ").append(toIndentedString(validNetworkServers)).append("\n");
    sb.append("    defaultChannelPlanId: ").append(toIndentedString(defaultChannelPlanId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

