/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import lora.ns.netmore.rest.model.ConfigId;
import lora.ns.netmore.rest.model.ConfigType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DeviceGroupConfig
 */
@JsonPropertyOrder({
  DeviceGroupConfig.JSON_PROPERTY_DEVICE_GROUP_ID,
  DeviceGroupConfig.JSON_PROPERTY_CONFIG_ID,
  DeviceGroupConfig.JSON_PROPERTY_CONFIG
})
public class DeviceGroupConfig {
  public static final String JSON_PROPERTY_DEVICE_GROUP_ID = "deviceGroupId";
  private String deviceGroupId;

  public static final String JSON_PROPERTY_CONFIG_ID = "configId";
  private ConfigId configId;

  public static final String JSON_PROPERTY_CONFIG = "config";
  private ConfigType config;

  public DeviceGroupConfig() {
  }

  public DeviceGroupConfig deviceGroupId(String deviceGroupId) {
    
    this.deviceGroupId = deviceGroupId;
    return this;
  }

   /**
   * Get deviceGroupId
   * @return deviceGroupId
  **/

  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeviceGroupId() {
    return deviceGroupId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeviceGroupId(String deviceGroupId) {
    this.deviceGroupId = deviceGroupId;
  }


  public DeviceGroupConfig configId(ConfigId configId) {
    
    this.configId = configId;
    return this;
  }

   /**
   * Get configId
   * @return configId
  **/

  @JsonProperty(JSON_PROPERTY_CONFIG_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ConfigId getConfigId() {
    return configId;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfigId(ConfigId configId) {
    this.configId = configId;
  }


  public DeviceGroupConfig config(ConfigType config) {
    
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/

  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ConfigType getConfig() {
    return config;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfig(ConfigType config) {
    this.config = config;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceGroupConfig deviceGroupConfig = (DeviceGroupConfig) o;
    return Objects.equals(this.deviceGroupId, deviceGroupConfig.deviceGroupId) &&
        Objects.equals(this.configId, deviceGroupConfig.configId) &&
        Objects.equals(this.config, deviceGroupConfig.config);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceGroupId, configId, config);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceGroupConfig {\n");
    sb.append("    deviceGroupId: ").append(toIndentedString(deviceGroupId)).append("\n");
    sb.append("    configId: ").append(toIndentedString(configId)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

