/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DownlinkRequestData
 */
@JsonPropertyOrder({
  DownlinkRequestData.JSON_PROPERTY_ID,
  DownlinkRequestData.JSON_PROPERTY_REQUEST_TIMESTAMP,
  DownlinkRequestData.JSON_PROPERTY_REQUEST_PAYLOAD_HEX,
  DownlinkRequestData.JSON_PROPERTY_REQUEST_F_PORT,
  DownlinkRequestData.JSON_PROPERTY_REQUEST_F_CNT,
  DownlinkRequestData.JSON_PROPERTY_RESPONSE_TIMESTAMP,
  DownlinkRequestData.JSON_PROPERTY_RESPONSE_ACTILITY_DATA,
  DownlinkRequestData.JSON_PROPERTY_DELIVERY_STATUS,
  DownlinkRequestData.JSON_PROPERTY_ERROR_CODE,
  DownlinkRequestData.JSON_PROPERTY_ERROR_DESCRIPTION,
  DownlinkRequestData.JSON_PROPERTY_REQUEST_ID,
  DownlinkRequestData.JSON_PROPERTY_MQTT,
  DownlinkRequestData.JSON_PROPERTY_FPORT,
  DownlinkRequestData.JSON_PROPERTY_FCNT
})
public class DownlinkRequestData {
  public static final String JSON_PROPERTY_ID = "id";
  private Double id;

  public static final String JSON_PROPERTY_REQUEST_TIMESTAMP = "requestTimestamp";
  private String requestTimestamp;

  public static final String JSON_PROPERTY_REQUEST_PAYLOAD_HEX = "requestPayloadHex";
  private String requestPayloadHex;

  public static final String JSON_PROPERTY_REQUEST_F_PORT = "requestFPort";
  private String requestFPort;

  public static final String JSON_PROPERTY_REQUEST_F_CNT = "requestFCnt";
  private Double requestFCnt;

  public static final String JSON_PROPERTY_RESPONSE_TIMESTAMP = "responseTimestamp";
  private String responseTimestamp;

  public static final String JSON_PROPERTY_RESPONSE_ACTILITY_DATA = "responseActilityData";
  private String responseActilityData;

  public static final String JSON_PROPERTY_DELIVERY_STATUS = "deliveryStatus";
  private String deliveryStatus;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR_DESCRIPTION = "errorDescription";
  private String errorDescription;

  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  private String requestId;

  public static final String JSON_PROPERTY_MQTT = "mqtt";
  private Boolean mqtt;

  public static final String JSON_PROPERTY_FPORT = "fport";
  private String fport;

  public static final String JSON_PROPERTY_FCNT = "fcnt";
  private Double fcnt;

  public DownlinkRequestData() {
  }

  public DownlinkRequestData id(Double id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Double id) {
    this.id = id;
  }


  public DownlinkRequestData requestTimestamp(String requestTimestamp) {
    
    this.requestTimestamp = requestTimestamp;
    return this;
  }

   /**
   * Get requestTimestamp
   * @return requestTimestamp
  **/

  @JsonProperty(JSON_PROPERTY_REQUEST_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRequestTimestamp() {
    return requestTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestTimestamp(String requestTimestamp) {
    this.requestTimestamp = requestTimestamp;
  }


  public DownlinkRequestData requestPayloadHex(String requestPayloadHex) {
    
    this.requestPayloadHex = requestPayloadHex;
    return this;
  }

   /**
   * Get requestPayloadHex
   * @return requestPayloadHex
  **/

  @JsonProperty(JSON_PROPERTY_REQUEST_PAYLOAD_HEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRequestPayloadHex() {
    return requestPayloadHex;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_PAYLOAD_HEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestPayloadHex(String requestPayloadHex) {
    this.requestPayloadHex = requestPayloadHex;
  }


  public DownlinkRequestData requestFPort(String requestFPort) {
    
    this.requestFPort = requestFPort;
    return this;
  }

   /**
   * Get requestFPort
   * @return requestFPort
  **/

  @JsonProperty(JSON_PROPERTY_REQUEST_F_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRequestFPort() {
    return requestFPort;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_F_PORT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestFPort(String requestFPort) {
    this.requestFPort = requestFPort;
  }


  public DownlinkRequestData requestFCnt(Double requestFCnt) {
    
    this.requestFCnt = requestFCnt;
    return this;
  }

   /**
   * Get requestFCnt
   * @return requestFCnt
  **/

  @JsonProperty(JSON_PROPERTY_REQUEST_F_CNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRequestFCnt() {
    return requestFCnt;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_F_CNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestFCnt(Double requestFCnt) {
    this.requestFCnt = requestFCnt;
  }


  public DownlinkRequestData responseTimestamp(String responseTimestamp) {
    
    this.responseTimestamp = responseTimestamp;
    return this;
  }

   /**
   * Get responseTimestamp
   * @return responseTimestamp
  **/

  @JsonProperty(JSON_PROPERTY_RESPONSE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResponseTimestamp() {
    return responseTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseTimestamp(String responseTimestamp) {
    this.responseTimestamp = responseTimestamp;
  }


  public DownlinkRequestData responseActilityData(String responseActilityData) {
    
    this.responseActilityData = responseActilityData;
    return this;
  }

   /**
   * Get responseActilityData
   * @return responseActilityData
  **/

  @JsonProperty(JSON_PROPERTY_RESPONSE_ACTILITY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResponseActilityData() {
    return responseActilityData;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSE_ACTILITY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseActilityData(String responseActilityData) {
    this.responseActilityData = responseActilityData;
  }


  public DownlinkRequestData deliveryStatus(String deliveryStatus) {
    
    this.deliveryStatus = deliveryStatus;
    return this;
  }

   /**
   * Get deliveryStatus
   * @return deliveryStatus
  **/

  @JsonProperty(JSON_PROPERTY_DELIVERY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeliveryStatus() {
    return deliveryStatus;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeliveryStatus(String deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }


  public DownlinkRequestData errorCode(String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/

  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorCode() {
    return errorCode;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }


  public DownlinkRequestData errorDescription(String errorDescription) {
    
    this.errorDescription = errorDescription;
    return this;
  }

   /**
   * Get errorDescription
   * @return errorDescription
  **/

  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorDescription() {
    return errorDescription;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorDescription(String errorDescription) {
    this.errorDescription = errorDescription;
  }


  public DownlinkRequestData requestId(String requestId) {
    
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/

  @JsonProperty(JSON_PROPERTY_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(String requestId) {
    this.requestId = requestId;
  }


  public DownlinkRequestData mqtt(Boolean mqtt) {
    
    this.mqtt = mqtt;
    return this;
  }

   /**
   * Get mqtt
   * @return mqtt
  **/

  @JsonProperty(JSON_PROPERTY_MQTT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMqtt() {
    return mqtt;
  }


  @JsonProperty(JSON_PROPERTY_MQTT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMqtt(Boolean mqtt) {
    this.mqtt = mqtt;
  }


  public DownlinkRequestData fport(String fport) {
    
    this.fport = fport;
    return this;
  }

   /**
   * Get fport
   * @return fport
  **/

  @JsonProperty(JSON_PROPERTY_FPORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFport() {
    return fport;
  }


  @JsonProperty(JSON_PROPERTY_FPORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFport(String fport) {
    this.fport = fport;
  }


  public DownlinkRequestData fcnt(Double fcnt) {
    
    this.fcnt = fcnt;
    return this;
  }

   /**
   * Get fcnt
   * @return fcnt
  **/

  @JsonProperty(JSON_PROPERTY_FCNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getFcnt() {
    return fcnt;
  }


  @JsonProperty(JSON_PROPERTY_FCNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFcnt(Double fcnt) {
    this.fcnt = fcnt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownlinkRequestData downlinkRequestData = (DownlinkRequestData) o;
    return Objects.equals(this.id, downlinkRequestData.id) &&
        Objects.equals(this.requestTimestamp, downlinkRequestData.requestTimestamp) &&
        Objects.equals(this.requestPayloadHex, downlinkRequestData.requestPayloadHex) &&
        Objects.equals(this.requestFPort, downlinkRequestData.requestFPort) &&
        Objects.equals(this.requestFCnt, downlinkRequestData.requestFCnt) &&
        Objects.equals(this.responseTimestamp, downlinkRequestData.responseTimestamp) &&
        Objects.equals(this.responseActilityData, downlinkRequestData.responseActilityData) &&
        Objects.equals(this.deliveryStatus, downlinkRequestData.deliveryStatus) &&
        Objects.equals(this.errorCode, downlinkRequestData.errorCode) &&
        Objects.equals(this.errorDescription, downlinkRequestData.errorDescription) &&
        Objects.equals(this.requestId, downlinkRequestData.requestId) &&
        Objects.equals(this.mqtt, downlinkRequestData.mqtt) &&
        Objects.equals(this.fport, downlinkRequestData.fport) &&
        Objects.equals(this.fcnt, downlinkRequestData.fcnt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, requestTimestamp, requestPayloadHex, requestFPort, requestFCnt, responseTimestamp, responseActilityData, deliveryStatus, errorCode, errorDescription, requestId, mqtt, fport, fcnt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownlinkRequestData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    requestTimestamp: ").append(toIndentedString(requestTimestamp)).append("\n");
    sb.append("    requestPayloadHex: ").append(toIndentedString(requestPayloadHex)).append("\n");
    sb.append("    requestFPort: ").append(toIndentedString(requestFPort)).append("\n");
    sb.append("    requestFCnt: ").append(toIndentedString(requestFCnt)).append("\n");
    sb.append("    responseTimestamp: ").append(toIndentedString(responseTimestamp)).append("\n");
    sb.append("    responseActilityData: ").append(toIndentedString(responseActilityData)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    mqtt: ").append(toIndentedString(mqtt)).append("\n");
    sb.append("    fport: ").append(toIndentedString(fport)).append("\n");
    sb.append("    fcnt: ").append(toIndentedString(fcnt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

