/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import lora.ns.netmore.rest.model.OutputLogEvent;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetFilterLogEventResponse
 */
@JsonPropertyOrder({
  GetFilterLogEventResponse.JSON_PROPERTY_EVENTS,
  GetFilterLogEventResponse.JSON_PROPERTY_NEXT_TOKEN
})
public class GetFilterLogEventResponse {
  public static final String JSON_PROPERTY_EVENTS = "events";
  private List<OutputLogEvent> events = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_TOKEN = "nextToken";
  private String nextToken;

  public GetFilterLogEventResponse() {
  }

  public GetFilterLogEventResponse events(List<OutputLogEvent> events) {
    
    this.events = events;
    return this;
  }

  public GetFilterLogEventResponse addEventsItem(OutputLogEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

   /**
   * Get events
   * @return events
  **/

  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<OutputLogEvent> getEvents() {
    return events;
  }


  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvents(List<OutputLogEvent> events) {
    this.events = events;
  }


  public GetFilterLogEventResponse nextToken(String nextToken) {
    
    this.nextToken = nextToken;
    return this;
  }

   /**
   * Get nextToken
   * @return nextToken
  **/

  @JsonProperty(JSON_PROPERTY_NEXT_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextToken() {
    return nextToken;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFilterLogEventResponse getFilterLogEventResponse = (GetFilterLogEventResponse) o;
    return Objects.equals(this.events, getFilterLogEventResponse.events) &&
        Objects.equals(this.nextToken, getFilterLogEventResponse.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(events, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFilterLogEventResponse {\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

