/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import lora.ns.netmore.rest.model.LoraServiceProviderCustomersInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LoraServiceProvider
 */
@JsonPropertyOrder({
  LoraServiceProvider.JSON_PROPERTY_DEVICE_GROUP_ID,
  LoraServiceProvider.JSON_PROPERTY_SERVICE_PROVIDER_ID,
  LoraServiceProvider.JSON_PROPERTY_SHARED,
  LoraServiceProvider.JSON_PROPERTY_USERNAME,
  LoraServiceProvider.JSON_PROPERTY_PASSWORD,
  LoraServiceProvider.JSON_PROPERTY_LAST_UPDATE,
  LoraServiceProvider.JSON_PROPERTY_CREATED,
  LoraServiceProvider.JSON_PROPERTY_CUSTOMERS,
  LoraServiceProvider.JSON_PROPERTY_CAN_CREATE_NEW
})
public class LoraServiceProvider {
  public static final String JSON_PROPERTY_DEVICE_GROUP_ID = "deviceGroupId";
  private String deviceGroupId;

  public static final String JSON_PROPERTY_SERVICE_PROVIDER_ID = "serviceProviderId";
  private String serviceProviderId;

  public static final String JSON_PROPERTY_SHARED = "shared";
  private Boolean shared;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private String username;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
  private String lastUpdate;

  public static final String JSON_PROPERTY_CREATED = "created";
  private String created;

  public static final String JSON_PROPERTY_CUSTOMERS = "customers";
  private List<LoraServiceProviderCustomersInner> customers = new ArrayList<>();

  public static final String JSON_PROPERTY_CAN_CREATE_NEW = "canCreateNew";
  private Boolean canCreateNew;

  public LoraServiceProvider() {
  }

  public LoraServiceProvider deviceGroupId(String deviceGroupId) {
    
    this.deviceGroupId = deviceGroupId;
    return this;
  }

   /**
   * Get deviceGroupId
   * @return deviceGroupId
  **/

  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeviceGroupId() {
    return deviceGroupId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeviceGroupId(String deviceGroupId) {
    this.deviceGroupId = deviceGroupId;
  }


  public LoraServiceProvider serviceProviderId(String serviceProviderId) {
    
    this.serviceProviderId = serviceProviderId;
    return this;
  }

   /**
   * Get serviceProviderId
   * @return serviceProviderId
  **/

  @JsonProperty(JSON_PROPERTY_SERVICE_PROVIDER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getServiceProviderId() {
    return serviceProviderId;
  }


  @JsonProperty(JSON_PROPERTY_SERVICE_PROVIDER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServiceProviderId(String serviceProviderId) {
    this.serviceProviderId = serviceProviderId;
  }


  public LoraServiceProvider shared(Boolean shared) {
    
    this.shared = shared;
    return this;
  }

   /**
   * Get shared
   * @return shared
  **/

  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getShared() {
    return shared;
  }


  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShared(Boolean shared) {
    this.shared = shared;
  }


  public LoraServiceProvider username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/

  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsername(String username) {
    this.username = username;
  }


  public LoraServiceProvider password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/

  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPassword(String password) {
    this.password = password;
  }


  public LoraServiceProvider lastUpdate(String lastUpdate) {
    
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Get lastUpdate
   * @return lastUpdate
  **/

  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastUpdate() {
    return lastUpdate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }


  public LoraServiceProvider created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/

  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(String created) {
    this.created = created;
  }


  public LoraServiceProvider customers(List<LoraServiceProviderCustomersInner> customers) {
    
    this.customers = customers;
    return this;
  }

  public LoraServiceProvider addCustomersItem(LoraServiceProviderCustomersInner customersItem) {
    if (this.customers == null) {
      this.customers = new ArrayList<>();
    }
    this.customers.add(customersItem);
    return this;
  }

   /**
   * This is the list of lora customer available for this service provider.
   * @return customers
  **/

  @JsonProperty(JSON_PROPERTY_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<LoraServiceProviderCustomersInner> getCustomers() {
    return customers;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomers(List<LoraServiceProviderCustomersInner> customers) {
    this.customers = customers;
  }


  public LoraServiceProvider canCreateNew(Boolean canCreateNew) {
    
    this.canCreateNew = canCreateNew;
    return this;
  }

   /**
   * Get canCreateNew
   * @return canCreateNew
  **/

  @JsonProperty(JSON_PROPERTY_CAN_CREATE_NEW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getCanCreateNew() {
    return canCreateNew;
  }


  @JsonProperty(JSON_PROPERTY_CAN_CREATE_NEW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCanCreateNew(Boolean canCreateNew) {
    this.canCreateNew = canCreateNew;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoraServiceProvider loraServiceProvider = (LoraServiceProvider) o;
    return Objects.equals(this.deviceGroupId, loraServiceProvider.deviceGroupId) &&
        Objects.equals(this.serviceProviderId, loraServiceProvider.serviceProviderId) &&
        Objects.equals(this.shared, loraServiceProvider.shared) &&
        Objects.equals(this.username, loraServiceProvider.username) &&
        Objects.equals(this.password, loraServiceProvider.password) &&
        Objects.equals(this.lastUpdate, loraServiceProvider.lastUpdate) &&
        Objects.equals(this.created, loraServiceProvider.created) &&
        Objects.equals(this.customers, loraServiceProvider.customers) &&
        Objects.equals(this.canCreateNew, loraServiceProvider.canCreateNew);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceGroupId, serviceProviderId, shared, username, password, lastUpdate, created, customers, canCreateNew);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoraServiceProvider {\n");
    sb.append("    deviceGroupId: ").append(toIndentedString(deviceGroupId)).append("\n");
    sb.append("    serviceProviderId: ").append(toIndentedString(serviceProviderId)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    customers: ").append(toIndentedString(customers)).append("\n");
    sb.append("    canCreateNew: ").append(toIndentedString(canCreateNew)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

