/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import lora.ns.netmore.rest.model.NbIotDeviceDetails;
import lora.ns.netmore.rest.model.NbIotOperatorDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NbIotDevice
 */
@JsonPropertyOrder({
  NbIotDevice.JSON_PROPERTY_NB_IOT_DEVICE_ID,
  NbIotDevice.JSON_PROPERTY_NETMORE_U_I_D3_G_P_P,
  NbIotDevice.JSON_PROPERTY_DETAILS,
  NbIotDevice.JSON_PROPERTY_OPERATOR,
  NbIotDevice.JSON_PROPERTY_CREATED,
  NbIotDevice.JSON_PROPERTY_LAST_UPDATED
})
public class NbIotDevice {
  public static final String JSON_PROPERTY_NB_IOT_DEVICE_ID = "nbIotDeviceId";
  private String nbIotDeviceId;

  public static final String JSON_PROPERTY_NETMORE_U_I_D3_G_P_P = "netmoreUID3GPP";
  private String netmoreUID3GPP;

  public static final String JSON_PROPERTY_DETAILS = "details";
  private NbIotDeviceDetails details;

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  private NbIotOperatorDetails operator;

  public static final String JSON_PROPERTY_CREATED = "created";
  private String created;

  public static final String JSON_PROPERTY_LAST_UPDATED = "lastUpdated";
  private String lastUpdated;

  public NbIotDevice() {
  }

  public NbIotDevice nbIotDeviceId(String nbIotDeviceId) {
    
    this.nbIotDeviceId = nbIotDeviceId;
    return this;
  }

   /**
   * Get nbIotDeviceId
   * @return nbIotDeviceId
  **/

  @JsonProperty(JSON_PROPERTY_NB_IOT_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNbIotDeviceId() {
    return nbIotDeviceId;
  }


  @JsonProperty(JSON_PROPERTY_NB_IOT_DEVICE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNbIotDeviceId(String nbIotDeviceId) {
    this.nbIotDeviceId = nbIotDeviceId;
  }


  public NbIotDevice netmoreUID3GPP(String netmoreUID3GPP) {
    
    this.netmoreUID3GPP = netmoreUID3GPP;
    return this;
  }

   /**
   * Get netmoreUID3GPP
   * @return netmoreUID3GPP
  **/

  @JsonProperty(JSON_PROPERTY_NETMORE_U_I_D3_G_P_P)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNetmoreUID3GPP() {
    return netmoreUID3GPP;
  }


  @JsonProperty(JSON_PROPERTY_NETMORE_U_I_D3_G_P_P)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetmoreUID3GPP(String netmoreUID3GPP) {
    this.netmoreUID3GPP = netmoreUID3GPP;
  }


  public NbIotDevice details(NbIotDeviceDetails details) {
    
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/

  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NbIotDeviceDetails getDetails() {
    return details;
  }


  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetails(NbIotDeviceDetails details) {
    this.details = details;
  }


  public NbIotDevice operator(NbIotOperatorDetails operator) {
    
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/

  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NbIotOperatorDetails getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperator(NbIotOperatorDetails operator) {
    this.operator = operator;
  }


  public NbIotDevice created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/

  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(String created) {
    this.created = created;
  }


  public NbIotDevice lastUpdated(String lastUpdated) {
    
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/

  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastUpdated() {
    return lastUpdated;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastUpdated(String lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NbIotDevice nbIotDevice = (NbIotDevice) o;
    return Objects.equals(this.nbIotDeviceId, nbIotDevice.nbIotDeviceId) &&
        Objects.equals(this.netmoreUID3GPP, nbIotDevice.netmoreUID3GPP) &&
        Objects.equals(this.details, nbIotDevice.details) &&
        Objects.equals(this.operator, nbIotDevice.operator) &&
        Objects.equals(this.created, nbIotDevice.created) &&
        Objects.equals(this.lastUpdated, nbIotDevice.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nbIotDeviceId, netmoreUID3GPP, details, operator, created, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NbIotDevice {\n");
    sb.append("    nbIotDeviceId: ").append(toIndentedString(nbIotDeviceId)).append("\n");
    sb.append("    netmoreUID3GPP: ").append(toIndentedString(netmoreUID3GPP)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

