/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import lora.ns.netmore.rest.model.UserRights;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PatchUserRequest
 */
@JsonPropertyOrder({
  PatchUserRequest.JSON_PROPERTY_FIRST_NAME,
  PatchUserRequest.JSON_PROPERTY_LAST_NAME,
  PatchUserRequest.JSON_PROPERTY_EMAIL,
  PatchUserRequest.JSON_PROPERTY_EMAIL_VERIFIED,
  PatchUserRequest.JSON_PROPERTY_RIGHTS,
  PatchUserRequest.JSON_PROPERTY_ENABLED,
  PatchUserRequest.JSON_PROPERTY_IDP_ENABLED,
  PatchUserRequest.JSON_PROPERTY_TOTP,
  PatchUserRequest.JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES,
  PatchUserRequest.JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES,
  PatchUserRequest.JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES,
  PatchUserRequest.JSON_PROPERTY_MAP_CENTER_LATITUDE,
  PatchUserRequest.JSON_PROPERTY_MAP_CENTER_LONGITUDE,
  PatchUserRequest.JSON_PROPERTY_MAP_ZOOM_LEVEL,
  PatchUserRequest.JSON_PROPERTY_CLIENT_ID
})
public class PatchUserRequest {
  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  private String lastName;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_EMAIL_VERIFIED = "emailVerified";
  private Boolean emailVerified;

  public static final String JSON_PROPERTY_RIGHTS = "rights";
  private List<UserRights> rights;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  private Boolean enabled;

  public static final String JSON_PROPERTY_IDP_ENABLED = "idpEnabled";
  private Boolean idpEnabled;

  public static final String JSON_PROPERTY_TOTP = "totp";
  private Boolean totp;

  public static final String JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES = "mailNotificationsDisturbances";
  private Boolean mailNotificationsDisturbances;

  public static final String JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES = "mailNotificationsReleaseNotes";
  private Boolean mailNotificationsReleaseNotes;

  public static final String JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES = "mailNotificationsUpcomingReleases";
  private Boolean mailNotificationsUpcomingReleases;

  public static final String JSON_PROPERTY_MAP_CENTER_LATITUDE = "mapCenterLatitude";
  private Double mapCenterLatitude;

  public static final String JSON_PROPERTY_MAP_CENTER_LONGITUDE = "mapCenterLongitude";
  private Double mapCenterLongitude;

  public static final String JSON_PROPERTY_MAP_ZOOM_LEVEL = "mapZoomLevel";
  private Double mapZoomLevel;

  public static final String JSON_PROPERTY_CLIENT_ID = "clientId";
  private String clientId;

  public PatchUserRequest() {
  }

  public PatchUserRequest firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/

  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public PatchUserRequest lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/

  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public PatchUserRequest email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/

  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public PatchUserRequest emailVerified(Boolean emailVerified) {
    
    this.emailVerified = emailVerified;
    return this;
  }

   /**
   * Get emailVerified
   * @return emailVerified
  **/

  @JsonProperty(JSON_PROPERTY_EMAIL_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEmailVerified() {
    return emailVerified;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailVerified(Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }


  public PatchUserRequest rights(List<UserRights> rights) {
    
    this.rights = rights;
    return this;
  }

  public PatchUserRequest addRightsItem(UserRights rightsItem) {
    if (this.rights == null) {
      this.rights = new ArrayList<>();
    }
    this.rights.add(rightsItem);
    return this;
  }

   /**
   * Get rights
   * @return rights
  **/

  @JsonProperty(JSON_PROPERTY_RIGHTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UserRights> getRights() {
    return rights;
  }


  @JsonProperty(JSON_PROPERTY_RIGHTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRights(List<UserRights> rights) {
    this.rights = rights;
  }


  public PatchUserRequest enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/

  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public PatchUserRequest idpEnabled(Boolean idpEnabled) {
    
    this.idpEnabled = idpEnabled;
    return this;
  }

   /**
   * Get idpEnabled
   * @return idpEnabled
  **/

  @JsonProperty(JSON_PROPERTY_IDP_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIdpEnabled() {
    return idpEnabled;
  }


  @JsonProperty(JSON_PROPERTY_IDP_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdpEnabled(Boolean idpEnabled) {
    this.idpEnabled = idpEnabled;
  }


  public PatchUserRequest totp(Boolean totp) {
    
    this.totp = totp;
    return this;
  }

   /**
   * Get totp
   * @return totp
  **/

  @JsonProperty(JSON_PROPERTY_TOTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTotp() {
    return totp;
  }


  @JsonProperty(JSON_PROPERTY_TOTP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotp(Boolean totp) {
    this.totp = totp;
  }


  public PatchUserRequest mailNotificationsDisturbances(Boolean mailNotificationsDisturbances) {
    
    this.mailNotificationsDisturbances = mailNotificationsDisturbances;
    return this;
  }

   /**
   * Get mailNotificationsDisturbances
   * @return mailNotificationsDisturbances
  **/

  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailNotificationsDisturbances() {
    return mailNotificationsDisturbances;
  }


  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_DISTURBANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailNotificationsDisturbances(Boolean mailNotificationsDisturbances) {
    this.mailNotificationsDisturbances = mailNotificationsDisturbances;
  }


  public PatchUserRequest mailNotificationsReleaseNotes(Boolean mailNotificationsReleaseNotes) {
    
    this.mailNotificationsReleaseNotes = mailNotificationsReleaseNotes;
    return this;
  }

   /**
   * Get mailNotificationsReleaseNotes
   * @return mailNotificationsReleaseNotes
  **/

  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailNotificationsReleaseNotes() {
    return mailNotificationsReleaseNotes;
  }


  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_RELEASE_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailNotificationsReleaseNotes(Boolean mailNotificationsReleaseNotes) {
    this.mailNotificationsReleaseNotes = mailNotificationsReleaseNotes;
  }


  public PatchUserRequest mailNotificationsUpcomingReleases(Boolean mailNotificationsUpcomingReleases) {
    
    this.mailNotificationsUpcomingReleases = mailNotificationsUpcomingReleases;
    return this;
  }

   /**
   * Get mailNotificationsUpcomingReleases
   * @return mailNotificationsUpcomingReleases
  **/

  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMailNotificationsUpcomingReleases() {
    return mailNotificationsUpcomingReleases;
  }


  @JsonProperty(JSON_PROPERTY_MAIL_NOTIFICATIONS_UPCOMING_RELEASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailNotificationsUpcomingReleases(Boolean mailNotificationsUpcomingReleases) {
    this.mailNotificationsUpcomingReleases = mailNotificationsUpcomingReleases;
  }


  public PatchUserRequest mapCenterLatitude(Double mapCenterLatitude) {
    
    this.mapCenterLatitude = mapCenterLatitude;
    return this;
  }

   /**
   * Get mapCenterLatitude
   * @return mapCenterLatitude
  **/

  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMapCenterLatitude() {
    return mapCenterLatitude;
  }


  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapCenterLatitude(Double mapCenterLatitude) {
    this.mapCenterLatitude = mapCenterLatitude;
  }


  public PatchUserRequest mapCenterLongitude(Double mapCenterLongitude) {
    
    this.mapCenterLongitude = mapCenterLongitude;
    return this;
  }

   /**
   * Get mapCenterLongitude
   * @return mapCenterLongitude
  **/

  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMapCenterLongitude() {
    return mapCenterLongitude;
  }


  @JsonProperty(JSON_PROPERTY_MAP_CENTER_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapCenterLongitude(Double mapCenterLongitude) {
    this.mapCenterLongitude = mapCenterLongitude;
  }


  public PatchUserRequest mapZoomLevel(Double mapZoomLevel) {
    
    this.mapZoomLevel = mapZoomLevel;
    return this;
  }

   /**
   * Get mapZoomLevel
   * @return mapZoomLevel
  **/

  @JsonProperty(JSON_PROPERTY_MAP_ZOOM_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMapZoomLevel() {
    return mapZoomLevel;
  }


  @JsonProperty(JSON_PROPERTY_MAP_ZOOM_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMapZoomLevel(Double mapZoomLevel) {
    this.mapZoomLevel = mapZoomLevel;
  }


  public PatchUserRequest clientId(String clientId) {
    
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/

  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientId() {
    return clientId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchUserRequest patchUserRequest = (PatchUserRequest) o;
    return Objects.equals(this.firstName, patchUserRequest.firstName) &&
        Objects.equals(this.lastName, patchUserRequest.lastName) &&
        Objects.equals(this.email, patchUserRequest.email) &&
        Objects.equals(this.emailVerified, patchUserRequest.emailVerified) &&
        Objects.equals(this.rights, patchUserRequest.rights) &&
        Objects.equals(this.enabled, patchUserRequest.enabled) &&
        Objects.equals(this.idpEnabled, patchUserRequest.idpEnabled) &&
        Objects.equals(this.totp, patchUserRequest.totp) &&
        Objects.equals(this.mailNotificationsDisturbances, patchUserRequest.mailNotificationsDisturbances) &&
        Objects.equals(this.mailNotificationsReleaseNotes, patchUserRequest.mailNotificationsReleaseNotes) &&
        Objects.equals(this.mailNotificationsUpcomingReleases, patchUserRequest.mailNotificationsUpcomingReleases) &&
        Objects.equals(this.mapCenterLatitude, patchUserRequest.mapCenterLatitude) &&
        Objects.equals(this.mapCenterLongitude, patchUserRequest.mapCenterLongitude) &&
        Objects.equals(this.mapZoomLevel, patchUserRequest.mapZoomLevel) &&
        Objects.equals(this.clientId, patchUserRequest.clientId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, email, emailVerified, rights, enabled, idpEnabled, totp, mailNotificationsDisturbances, mailNotificationsReleaseNotes, mailNotificationsUpcomingReleases, mapCenterLatitude, mapCenterLongitude, mapZoomLevel, clientId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchUserRequest {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
    sb.append("    rights: ").append(toIndentedString(rights)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    idpEnabled: ").append(toIndentedString(idpEnabled)).append("\n");
    sb.append("    totp: ").append(toIndentedString(totp)).append("\n");
    sb.append("    mailNotificationsDisturbances: ").append(toIndentedString(mailNotificationsDisturbances)).append("\n");
    sb.append("    mailNotificationsReleaseNotes: ").append(toIndentedString(mailNotificationsReleaseNotes)).append("\n");
    sb.append("    mailNotificationsUpcomingReleases: ").append(toIndentedString(mailNotificationsUpcomingReleases)).append("\n");
    sb.append("    mapCenterLatitude: ").append(toIndentedString(mapCenterLatitude)).append("\n");
    sb.append("    mapCenterLongitude: ").append(toIndentedString(mapCenterLongitude)).append("\n");
    sb.append("    mapZoomLevel: ").append(toIndentedString(mapZoomLevel)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

