/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lora.ns.netmore.rest.model.DeviceType;
import lora.ns.netmore.rest.model.Location;
import lora.ns.netmore.rest.model.NbIotUpdateNbDevices;
import lora.ns.netmore.rest.model.PatchLoraDevice;
import lora.ns.netmore.rest.model.PlacementType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PatchDeviceRequest
 */
@JsonPropertyOrder({
  PatchDeviceRequest.JSON_PROPERTY_NAME,
  PatchDeviceRequest.JSON_PROPERTY_PROPERTY_ID,
  PatchDeviceRequest.JSON_PROPERTY_BUILDING_ID,
  PatchDeviceRequest.JSON_PROPERTY_SPACE_ID,
  PatchDeviceRequest.JSON_PROPERTY_NOTE,
  PatchDeviceRequest.JSON_PROPERTY_HEART_BEAT,
  PatchDeviceRequest.JSON_PROPERTY_DEVICE_TYPE,
  PatchDeviceRequest.JSON_PROPERTY_DELETED,
  PatchDeviceRequest.JSON_PROPERTY_TAGS,
  PatchDeviceRequest.JSON_PROPERTY_LOCATION,
  PatchDeviceRequest.JSON_PROPERTY_NB_IOT_DEVICE,
  PatchDeviceRequest.JSON_PROPERTY_LORA_DEVICE,
  PatchDeviceRequest.JSON_PROPERTY_SERIAL_NUMBER,
  PatchDeviceRequest.JSON_PROPERTY_SENSOR_TYPE_ID,
  PatchDeviceRequest.JSON_PROPERTY_ONLINE,
  PatchDeviceRequest.JSON_PROPERTY_INSTALLED,
  PatchDeviceRequest.JSON_PROPERTY_PLACEMENT_TYPE,
  PatchDeviceRequest.JSON_PROPERTY_FIRMWARE_VERSION,
  PatchDeviceRequest.JSON_PROPERTY_EXPORT_CONFIG_GROUP_ID
})
public class PatchDeviceRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PROPERTY_ID = "propertyId";
  private String propertyId;

  public static final String JSON_PROPERTY_BUILDING_ID = "buildingId";
  private String buildingId;

  public static final String JSON_PROPERTY_SPACE_ID = "spaceId";
  private String spaceId;

  public static final String JSON_PROPERTY_NOTE = "note";
  private String note;

  public static final String JSON_PROPERTY_HEART_BEAT = "heartBeat";
  private Double heartBeat;

  public static final String JSON_PROPERTY_DEVICE_TYPE = "deviceType";
  private DeviceType deviceType;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private Map<String, List<String>> tags = new HashMap<>();

  public static final String JSON_PROPERTY_LOCATION = "location";
  private Location location;

  public static final String JSON_PROPERTY_NB_IOT_DEVICE = "nbIotDevice";
  private NbIotUpdateNbDevices nbIotDevice;

  public static final String JSON_PROPERTY_LORA_DEVICE = "loraDevice";
  private PatchLoraDevice loraDevice;

  public static final String JSON_PROPERTY_SERIAL_NUMBER = "serialNumber";
  private String serialNumber;

  public static final String JSON_PROPERTY_SENSOR_TYPE_ID = "sensorTypeId";
  private String sensorTypeId;

  public static final String JSON_PROPERTY_ONLINE = "online";
  private Boolean online;

  public static final String JSON_PROPERTY_INSTALLED = "installed";
  private Boolean installed;

  public static final String JSON_PROPERTY_PLACEMENT_TYPE = "placementType";
  private PlacementType placementType;

  public static final String JSON_PROPERTY_FIRMWARE_VERSION = "firmwareVersion";
  private String firmwareVersion;

  public static final String JSON_PROPERTY_EXPORT_CONFIG_GROUP_ID = "exportConfigGroupId";
  private String exportConfigGroupId;

  public PatchDeviceRequest() {
  }

  public PatchDeviceRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public PatchDeviceRequest propertyId(String propertyId) {
    
    this.propertyId = propertyId;
    return this;
  }

   /**
   * Get propertyId
   * @return propertyId
   * @deprecated
  **/
  @Deprecated

  @JsonProperty(JSON_PROPERTY_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPropertyId() {
    return propertyId;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyId(String propertyId) {
    this.propertyId = propertyId;
  }


  public PatchDeviceRequest buildingId(String buildingId) {
    
    this.buildingId = buildingId;
    return this;
  }

   /**
   * Get buildingId
   * @return buildingId
   * @deprecated
  **/
  @Deprecated

  @JsonProperty(JSON_PROPERTY_BUILDING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBuildingId() {
    return buildingId;
  }


  @JsonProperty(JSON_PROPERTY_BUILDING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuildingId(String buildingId) {
    this.buildingId = buildingId;
  }


  public PatchDeviceRequest spaceId(String spaceId) {
    
    this.spaceId = spaceId;
    return this;
  }

   /**
   * Get spaceId
   * @return spaceId
   * @deprecated
  **/
  @Deprecated

  @JsonProperty(JSON_PROPERTY_SPACE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpaceId() {
    return spaceId;
  }


  @JsonProperty(JSON_PROPERTY_SPACE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpaceId(String spaceId) {
    this.spaceId = spaceId;
  }


  public PatchDeviceRequest note(String note) {
    
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/

  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNote() {
    return note;
  }


  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNote(String note) {
    this.note = note;
  }


  public PatchDeviceRequest heartBeat(Double heartBeat) {
    
    this.heartBeat = heartBeat;
    return this;
  }

   /**
   * Get heartBeat
   * @return heartBeat
  **/

  @JsonProperty(JSON_PROPERTY_HEART_BEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getHeartBeat() {
    return heartBeat;
  }


  @JsonProperty(JSON_PROPERTY_HEART_BEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeartBeat(Double heartBeat) {
    this.heartBeat = heartBeat;
  }


  public PatchDeviceRequest deviceType(DeviceType deviceType) {
    
    this.deviceType = deviceType;
    return this;
  }

   /**
   * Get deviceType
   * @return deviceType
  **/

  @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceType getDeviceType() {
    return deviceType;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceType(DeviceType deviceType) {
    this.deviceType = deviceType;
  }


  public PatchDeviceRequest deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * To delete device a lora device you have to unprovision and uninstall it first.
   * @return deleted
  **/

  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public PatchDeviceRequest tags(Map<String, List<String>> tags) {
    
    this.tags = tags;
    return this;
  }

  public PatchDeviceRequest putTagsItem(String key, List<String> tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<String>> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(Map<String, List<String>> tags) {
    this.tags = tags;
  }


  public PatchDeviceRequest location(Location location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/

  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Location getLocation() {
    return location;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(Location location) {
    this.location = location;
  }


  public PatchDeviceRequest nbIotDevice(NbIotUpdateNbDevices nbIotDevice) {
    
    this.nbIotDevice = nbIotDevice;
    return this;
  }

   /**
   * Get nbIotDevice
   * @return nbIotDevice
  **/

  @JsonProperty(JSON_PROPERTY_NB_IOT_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NbIotUpdateNbDevices getNbIotDevice() {
    return nbIotDevice;
  }


  @JsonProperty(JSON_PROPERTY_NB_IOT_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNbIotDevice(NbIotUpdateNbDevices nbIotDevice) {
    this.nbIotDevice = nbIotDevice;
  }


  public PatchDeviceRequest loraDevice(PatchLoraDevice loraDevice) {
    
    this.loraDevice = loraDevice;
    return this;
  }

   /**
   * Get loraDevice
   * @return loraDevice
  **/

  @JsonProperty(JSON_PROPERTY_LORA_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PatchLoraDevice getLoraDevice() {
    return loraDevice;
  }


  @JsonProperty(JSON_PROPERTY_LORA_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoraDevice(PatchLoraDevice loraDevice) {
    this.loraDevice = loraDevice;
  }


  public PatchDeviceRequest serialNumber(String serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/

  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSerialNumber() {
    return serialNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  public PatchDeviceRequest sensorTypeId(String sensorTypeId) {
    
    this.sensorTypeId = sensorTypeId;
    return this;
  }

   /**
   * Get sensorTypeId
   * @return sensorTypeId
  **/

  @JsonProperty(JSON_PROPERTY_SENSOR_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSensorTypeId() {
    return sensorTypeId;
  }


  @JsonProperty(JSON_PROPERTY_SENSOR_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSensorTypeId(String sensorTypeId) {
    this.sensorTypeId = sensorTypeId;
  }


  public PatchDeviceRequest online(Boolean online) {
    
    this.online = online;
    return this;
  }

   /**
   * Get online
   * @return online
  **/

  @JsonProperty(JSON_PROPERTY_ONLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOnline() {
    return online;
  }


  @JsonProperty(JSON_PROPERTY_ONLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOnline(Boolean online) {
    this.online = online;
  }


  public PatchDeviceRequest installed(Boolean installed) {
    
    this.installed = installed;
    return this;
  }

   /**
   * Get installed
   * @return installed
  **/

  @JsonProperty(JSON_PROPERTY_INSTALLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInstalled() {
    return installed;
  }


  @JsonProperty(JSON_PROPERTY_INSTALLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInstalled(Boolean installed) {
    this.installed = installed;
  }


  public PatchDeviceRequest placementType(PlacementType placementType) {
    
    this.placementType = placementType;
    return this;
  }

   /**
   * Get placementType
   * @return placementType
  **/

  @JsonProperty(JSON_PROPERTY_PLACEMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PlacementType getPlacementType() {
    return placementType;
  }


  @JsonProperty(JSON_PROPERTY_PLACEMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlacementType(PlacementType placementType) {
    this.placementType = placementType;
  }


  public PatchDeviceRequest firmwareVersion(String firmwareVersion) {
    
    this.firmwareVersion = firmwareVersion;
    return this;
  }

   /**
   * Get firmwareVersion
   * @return firmwareVersion
  **/

  @JsonProperty(JSON_PROPERTY_FIRMWARE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirmwareVersion() {
    return firmwareVersion;
  }


  @JsonProperty(JSON_PROPERTY_FIRMWARE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirmwareVersion(String firmwareVersion) {
    this.firmwareVersion = firmwareVersion;
  }


  public PatchDeviceRequest exportConfigGroupId(String exportConfigGroupId) {
    
    this.exportConfigGroupId = exportConfigGroupId;
    return this;
  }

   /**
   * Get exportConfigGroupId
   * @return exportConfigGroupId
  **/

  @JsonProperty(JSON_PROPERTY_EXPORT_CONFIG_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExportConfigGroupId() {
    return exportConfigGroupId;
  }


  @JsonProperty(JSON_PROPERTY_EXPORT_CONFIG_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportConfigGroupId(String exportConfigGroupId) {
    this.exportConfigGroupId = exportConfigGroupId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchDeviceRequest patchDeviceRequest = (PatchDeviceRequest) o;
    return Objects.equals(this.name, patchDeviceRequest.name) &&
        Objects.equals(this.propertyId, patchDeviceRequest.propertyId) &&
        Objects.equals(this.buildingId, patchDeviceRequest.buildingId) &&
        Objects.equals(this.spaceId, patchDeviceRequest.spaceId) &&
        Objects.equals(this.note, patchDeviceRequest.note) &&
        Objects.equals(this.heartBeat, patchDeviceRequest.heartBeat) &&
        Objects.equals(this.deviceType, patchDeviceRequest.deviceType) &&
        Objects.equals(this.deleted, patchDeviceRequest.deleted) &&
        Objects.equals(this.tags, patchDeviceRequest.tags) &&
        Objects.equals(this.location, patchDeviceRequest.location) &&
        Objects.equals(this.nbIotDevice, patchDeviceRequest.nbIotDevice) &&
        Objects.equals(this.loraDevice, patchDeviceRequest.loraDevice) &&
        Objects.equals(this.serialNumber, patchDeviceRequest.serialNumber) &&
        Objects.equals(this.sensorTypeId, patchDeviceRequest.sensorTypeId) &&
        Objects.equals(this.online, patchDeviceRequest.online) &&
        Objects.equals(this.installed, patchDeviceRequest.installed) &&
        Objects.equals(this.placementType, patchDeviceRequest.placementType) &&
        Objects.equals(this.firmwareVersion, patchDeviceRequest.firmwareVersion) &&
        Objects.equals(this.exportConfigGroupId, patchDeviceRequest.exportConfigGroupId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, propertyId, buildingId, spaceId, note, heartBeat, deviceType, deleted, tags, location, nbIotDevice, loraDevice, serialNumber, sensorTypeId, online, installed, placementType, firmwareVersion, exportConfigGroupId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchDeviceRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    buildingId: ").append(toIndentedString(buildingId)).append("\n");
    sb.append("    spaceId: ").append(toIndentedString(spaceId)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    heartBeat: ").append(toIndentedString(heartBeat)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    nbIotDevice: ").append(toIndentedString(nbIotDevice)).append("\n");
    sb.append("    loraDevice: ").append(toIndentedString(loraDevice)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    sensorTypeId: ").append(toIndentedString(sensorTypeId)).append("\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("    installed: ").append(toIndentedString(installed)).append("\n");
    sb.append("    placementType: ").append(toIndentedString(placementType)).append("\n");
    sb.append("    firmwareVersion: ").append(toIndentedString(firmwareVersion)).append("\n");
    sb.append("    exportConfigGroupId: ").append(toIndentedString(exportConfigGroupId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

