/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import lora.ns.netmore.rest.model.AccessAttributes;
import lora.ns.netmore.rest.model.Roles;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * From T, pick a set of properties whose keys are in the union K
 */
@JsonPropertyOrder({
  PickAccessExcludeKeyofAccessExportConfigIds.JSON_PROPERTY_ACCESS_ID,
  PickAccessExcludeKeyofAccessExportConfigIds.JSON_PROPERTY_DEVICE_GROUP_ID,
  PickAccessExcludeKeyofAccessExportConfigIds.JSON_PROPERTY_CUSTOMER_ID,
  PickAccessExcludeKeyofAccessExportConfigIds.JSON_PROPERTY_ATTRIBUTES,
  PickAccessExcludeKeyofAccessExportConfigIds.JSON_PROPERTY_ROLE
})
@JsonTypeName("Pick_Access.Exclude_keyofAccess.exportConfigIds__")
public class PickAccessExcludeKeyofAccessExportConfigIds {
  public static final String JSON_PROPERTY_ACCESS_ID = "accessId";
  private String accessId;

  public static final String JSON_PROPERTY_DEVICE_GROUP_ID = "deviceGroupId";
  private String deviceGroupId;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private String customerId;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private AccessAttributes attributes;

  public static final String JSON_PROPERTY_ROLE = "role";
  private Roles role;

  public PickAccessExcludeKeyofAccessExportConfigIds() {
  }

  public PickAccessExcludeKeyofAccessExportConfigIds accessId(String accessId) {
    
    this.accessId = accessId;
    return this;
  }

   /**
   * Uniq id
   * @return accessId
  **/

  @JsonProperty(JSON_PROPERTY_ACCESS_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAccessId() {
    return accessId;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccessId(String accessId) {
    this.accessId = accessId;
  }


  public PickAccessExcludeKeyofAccessExportConfigIds deviceGroupId(String deviceGroupId) {
    
    this.deviceGroupId = deviceGroupId;
    return this;
  }

   /**
   * Id of the edge node.
   * @return deviceGroupId
  **/

  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeviceGroupId() {
    return deviceGroupId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeviceGroupId(String deviceGroupId) {
    this.deviceGroupId = deviceGroupId;
  }


  public PickAccessExcludeKeyofAccessExportConfigIds customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Customer id
   * @return customerId
  **/

  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public PickAccessExcludeKeyofAccessExportConfigIds attributes(AccessAttributes attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccessAttributes getAttributes() {
    return attributes;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAttributes(AccessAttributes attributes) {
    this.attributes = attributes;
  }


  public PickAccessExcludeKeyofAccessExportConfigIds role(Roles role) {
    
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/

  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Roles getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(Roles role) {
    this.role = role;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PickAccessExcludeKeyofAccessExportConfigIds pickAccessExcludeKeyofAccessExportConfigIds = (PickAccessExcludeKeyofAccessExportConfigIds) o;
    return Objects.equals(this.accessId, pickAccessExcludeKeyofAccessExportConfigIds.accessId) &&
        Objects.equals(this.deviceGroupId, pickAccessExcludeKeyofAccessExportConfigIds.deviceGroupId) &&
        Objects.equals(this.customerId, pickAccessExcludeKeyofAccessExportConfigIds.customerId) &&
        Objects.equals(this.attributes, pickAccessExcludeKeyofAccessExportConfigIds.attributes) &&
        Objects.equals(this.role, pickAccessExcludeKeyofAccessExportConfigIds.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessId, deviceGroupId, customerId, attributes, role);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PickAccessExcludeKeyofAccessExportConfigIds {\n");
    sb.append("    accessId: ").append(toIndentedString(accessId)).append("\n");
    sb.append("    deviceGroupId: ").append(toIndentedString(deviceGroupId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

