/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import lora.ns.netmore.rest.model.Roles;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RequestDeviceGroupAccess
 */
@JsonPropertyOrder({
  RequestDeviceGroupAccess.JSON_PROPERTY_DEVICE_GROUP_ID,
  RequestDeviceGroupAccess.JSON_PROPERTY_CUSTOMER_ID,
  RequestDeviceGroupAccess.JSON_PROPERTY_EXPORT_CONFIG_IDS,
  RequestDeviceGroupAccess.JSON_PROPERTY_ROLE
})
public class RequestDeviceGroupAccess {
  public static final String JSON_PROPERTY_DEVICE_GROUP_ID = "deviceGroupId";
  private String deviceGroupId;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private String customerId;

  public static final String JSON_PROPERTY_EXPORT_CONFIG_IDS = "exportConfigIds";
  private List<String> exportConfigIds;

  public static final String JSON_PROPERTY_ROLE = "role";
  private Roles role;

  public RequestDeviceGroupAccess() {
  }

  public RequestDeviceGroupAccess deviceGroupId(String deviceGroupId) {
    
    this.deviceGroupId = deviceGroupId;
    return this;
  }

   /**
   * Device group id to request access to.
   * @return deviceGroupId
  **/

  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeviceGroupId() {
    return deviceGroupId;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_GROUP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeviceGroupId(String deviceGroupId) {
    this.deviceGroupId = deviceGroupId;
  }


  public RequestDeviceGroupAccess customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * customerId for the new access.
   * @return customerId
  **/

  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public RequestDeviceGroupAccess exportConfigIds(List<String> exportConfigIds) {
    
    this.exportConfigIds = exportConfigIds;
    return this;
  }

  public RequestDeviceGroupAccess addExportConfigIdsItem(String exportConfigIdsItem) {
    if (this.exportConfigIds == null) {
      this.exportConfigIds = new ArrayList<>();
    }
    this.exportConfigIds.add(exportConfigIdsItem);
    return this;
  }

   /**
   * Export config ids that the customer wants to use for this device group.
   * @return exportConfigIds
  **/

  @JsonProperty(JSON_PROPERTY_EXPORT_CONFIG_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExportConfigIds() {
    return exportConfigIds;
  }


  @JsonProperty(JSON_PROPERTY_EXPORT_CONFIG_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportConfigIds(List<String> exportConfigIds) {
    this.exportConfigIds = exportConfigIds;
  }


  public RequestDeviceGroupAccess role(Roles role) {
    
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/

  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Roles getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(Roles role) {
    this.role = role;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestDeviceGroupAccess requestDeviceGroupAccess = (RequestDeviceGroupAccess) o;
    return Objects.equals(this.deviceGroupId, requestDeviceGroupAccess.deviceGroupId) &&
        Objects.equals(this.customerId, requestDeviceGroupAccess.customerId) &&
        Objects.equals(this.exportConfigIds, requestDeviceGroupAccess.exportConfigIds) &&
        Objects.equals(this.role, requestDeviceGroupAccess.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceGroupId, customerId, exportConfigIds, role);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestDeviceGroupAccess {\n");
    sb.append("    deviceGroupId: ").append(toIndentedString(deviceGroupId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    exportConfigIds: ").append(toIndentedString(exportConfigIds)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

