/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import lora.ns.netmore.rest.model.ActivationMethod;
import lora.ns.netmore.rest.model.ModelClass;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SearchLoraDevice
 */
@JsonPropertyOrder({
  SearchLoraDevice.JSON_PROPERTY_DEV_EUI,
  SearchLoraDevice.JSON_PROPERTY_ACTIVE,
  SearchLoraDevice.JSON_PROPERTY_ACTIVATION_METHOD,
  SearchLoraDevice.JSON_PROPERTY_PROPERTY_CLASS,
  SearchLoraDevice.JSON_PROPERTY_LORA_VERSION,
  SearchLoraDevice.JSON_PROPERTY_FIRST_COMM_TIMESTAMP,
  SearchLoraDevice.JSON_PROPERTY_LATEST_COMM_TIMESTAMP,
  SearchLoraDevice.JSON_PROPERTY_PROVISIONED,
  SearchLoraDevice.JSON_PROPERTY_APP_EUI,
  SearchLoraDevice.JSON_PROPERTY_DEV_ADDR
})
public class SearchLoraDevice {
  public static final String JSON_PROPERTY_DEV_EUI = "devEui";
  private String devEui;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active;

  public static final String JSON_PROPERTY_ACTIVATION_METHOD = "activationMethod";
  private ActivationMethod activationMethod;

  public static final String JSON_PROPERTY_PROPERTY_CLASS = "class";
  private ModelClass propertyClass;

  public static final String JSON_PROPERTY_LORA_VERSION = "loraVersion";
  private String loraVersion;

  public static final String JSON_PROPERTY_FIRST_COMM_TIMESTAMP = "firstCommTimestamp";
  private String firstCommTimestamp;

  public static final String JSON_PROPERTY_LATEST_COMM_TIMESTAMP = "latestCommTimestamp";
  private String latestCommTimestamp;

  public static final String JSON_PROPERTY_PROVISIONED = "provisioned";
  private Boolean provisioned;

  public static final String JSON_PROPERTY_APP_EUI = "appEui";
  private String appEui;

  public static final String JSON_PROPERTY_DEV_ADDR = "devAddr";
  private String devAddr;

  public SearchLoraDevice() {
  }

  public SearchLoraDevice devEui(String devEui) {
    
    this.devEui = devEui;
    return this;
  }

   /**
   * Get devEui
   * @return devEui
  **/

  @JsonProperty(JSON_PROPERTY_DEV_EUI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDevEui() {
    return devEui;
  }


  @JsonProperty(JSON_PROPERTY_DEV_EUI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevEui(String devEui) {
    this.devEui = devEui;
  }


  public SearchLoraDevice active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/

  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public SearchLoraDevice activationMethod(ActivationMethod activationMethod) {
    
    this.activationMethod = activationMethod;
    return this;
  }

   /**
   * Get activationMethod
   * @return activationMethod
  **/

  @JsonProperty(JSON_PROPERTY_ACTIVATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActivationMethod getActivationMethod() {
    return activationMethod;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVATION_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActivationMethod(ActivationMethod activationMethod) {
    this.activationMethod = activationMethod;
  }


  public SearchLoraDevice propertyClass(ModelClass propertyClass) {
    
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Get propertyClass
   * @return propertyClass
  **/

  @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModelClass getPropertyClass() {
    return propertyClass;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyClass(ModelClass propertyClass) {
    this.propertyClass = propertyClass;
  }


  public SearchLoraDevice loraVersion(String loraVersion) {
    
    this.loraVersion = loraVersion;
    return this;
  }

   /**
   * Get loraVersion
   * @return loraVersion
  **/

  @JsonProperty(JSON_PROPERTY_LORA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoraVersion() {
    return loraVersion;
  }


  @JsonProperty(JSON_PROPERTY_LORA_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoraVersion(String loraVersion) {
    this.loraVersion = loraVersion;
  }


  public SearchLoraDevice firstCommTimestamp(String firstCommTimestamp) {
    
    this.firstCommTimestamp = firstCommTimestamp;
    return this;
  }

   /**
   * Get firstCommTimestamp
   * @return firstCommTimestamp
  **/

  @JsonProperty(JSON_PROPERTY_FIRST_COMM_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstCommTimestamp() {
    return firstCommTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_COMM_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstCommTimestamp(String firstCommTimestamp) {
    this.firstCommTimestamp = firstCommTimestamp;
  }


  public SearchLoraDevice latestCommTimestamp(String latestCommTimestamp) {
    
    this.latestCommTimestamp = latestCommTimestamp;
    return this;
  }

   /**
   * Get latestCommTimestamp
   * @return latestCommTimestamp
  **/

  @JsonProperty(JSON_PROPERTY_LATEST_COMM_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLatestCommTimestamp() {
    return latestCommTimestamp;
  }


  @JsonProperty(JSON_PROPERTY_LATEST_COMM_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestCommTimestamp(String latestCommTimestamp) {
    this.latestCommTimestamp = latestCommTimestamp;
  }


  public SearchLoraDevice provisioned(Boolean provisioned) {
    
    this.provisioned = provisioned;
    return this;
  }

   /**
   * Get provisioned
   * @return provisioned
  **/

  @JsonProperty(JSON_PROPERTY_PROVISIONED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getProvisioned() {
    return provisioned;
  }


  @JsonProperty(JSON_PROPERTY_PROVISIONED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvisioned(Boolean provisioned) {
    this.provisioned = provisioned;
  }


  public SearchLoraDevice appEui(String appEui) {
    
    this.appEui = appEui;
    return this;
  }

   /**
   * Get appEui
   * @return appEui
  **/

  @JsonProperty(JSON_PROPERTY_APP_EUI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppEui() {
    return appEui;
  }


  @JsonProperty(JSON_PROPERTY_APP_EUI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppEui(String appEui) {
    this.appEui = appEui;
  }


  public SearchLoraDevice devAddr(String devAddr) {
    
    this.devAddr = devAddr;
    return this;
  }

   /**
   * Get devAddr
   * @return devAddr
  **/

  @JsonProperty(JSON_PROPERTY_DEV_ADDR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDevAddr() {
    return devAddr;
  }


  @JsonProperty(JSON_PROPERTY_DEV_ADDR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevAddr(String devAddr) {
    this.devAddr = devAddr;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchLoraDevice searchLoraDevice = (SearchLoraDevice) o;
    return Objects.equals(this.devEui, searchLoraDevice.devEui) &&
        Objects.equals(this.active, searchLoraDevice.active) &&
        Objects.equals(this.activationMethod, searchLoraDevice.activationMethod) &&
        Objects.equals(this.propertyClass, searchLoraDevice.propertyClass) &&
        Objects.equals(this.loraVersion, searchLoraDevice.loraVersion) &&
        Objects.equals(this.firstCommTimestamp, searchLoraDevice.firstCommTimestamp) &&
        Objects.equals(this.latestCommTimestamp, searchLoraDevice.latestCommTimestamp) &&
        Objects.equals(this.provisioned, searchLoraDevice.provisioned) &&
        Objects.equals(this.appEui, searchLoraDevice.appEui) &&
        Objects.equals(this.devAddr, searchLoraDevice.devAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(devEui, active, activationMethod, propertyClass, loraVersion, firstCommTimestamp, latestCommTimestamp, provisioned, appEui, devAddr);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchLoraDevice {\n");
    sb.append("    devEui: ").append(toIndentedString(devEui)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    activationMethod: ").append(toIndentedString(activationMethod)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    loraVersion: ").append(toIndentedString(loraVersion)).append("\n");
    sb.append("    firstCommTimestamp: ").append(toIndentedString(firstCommTimestamp)).append("\n");
    sb.append("    latestCommTimestamp: ").append(toIndentedString(latestCommTimestamp)).append("\n");
    sb.append("    provisioned: ").append(toIndentedString(provisioned)).append("\n");
    sb.append("    appEui: ").append(toIndentedString(appEui)).append("\n");
    sb.append("    devAddr: ").append(toIndentedString(devAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

