/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UpdateExportConfigGroupRequest
 */
@JsonPropertyOrder({
  UpdateExportConfigGroupRequest.JSON_PROPERTY_NAME,
  UpdateExportConfigGroupRequest.JSON_PROPERTY_AVAILABLE_TO_SUB_CUSTOMER,
  UpdateExportConfigGroupRequest.JSON_PROPERTY_EXPORT_CONFIGS
})
public class UpdateExportConfigGroupRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_AVAILABLE_TO_SUB_CUSTOMER = "availableToSubCustomer";
  private Boolean availableToSubCustomer;

  public static final String JSON_PROPERTY_EXPORT_CONFIGS = "exportConfigs";
  private List<String> exportConfigs;

  public UpdateExportConfigGroupRequest() {
  }

  public UpdateExportConfigGroupRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  @JsonProperty(JSON_PROPERTY_NAME)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName(String name) {
    this.name = name;
  }


  public UpdateExportConfigGroupRequest availableToSubCustomer(Boolean availableToSubCustomer) {
    
    this.availableToSubCustomer = availableToSubCustomer;
    return this;
  }

   /**
   * Get availableToSubCustomer
   * @return availableToSubCustomer
  **/

  @JsonProperty(JSON_PROPERTY_AVAILABLE_TO_SUB_CUSTOMER)

  public Boolean getAvailableToSubCustomer() {
    return availableToSubCustomer;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE_TO_SUB_CUSTOMER)
  public void setAvailableToSubCustomer(Boolean availableToSubCustomer) {
    this.availableToSubCustomer = availableToSubCustomer;
  }


  public UpdateExportConfigGroupRequest exportConfigs(List<String> exportConfigs) {
    
    this.exportConfigs = exportConfigs;
    return this;
  }

  public UpdateExportConfigGroupRequest addExportConfigsItem(String exportConfigsItem) {
    if (this.exportConfigs == null) {
      this.exportConfigs = new ArrayList<>();
    }
    this.exportConfigs.add(exportConfigsItem);
    return this;
  }

   /**
   * Get exportConfigs
   * @return exportConfigs
  **/

  @JsonProperty(JSON_PROPERTY_EXPORT_CONFIGS)

  public List<String> getExportConfigs() {
    return exportConfigs;
  }


  @JsonProperty(JSON_PROPERTY_EXPORT_CONFIGS)
  public void setExportConfigs(List<String> exportConfigs) {
    this.exportConfigs = exportConfigs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateExportConfigGroupRequest updateExportConfigGroupRequest = (UpdateExportConfigGroupRequest) o;
    return Objects.equals(this.name, updateExportConfigGroupRequest.name) &&
        Objects.equals(this.availableToSubCustomer, updateExportConfigGroupRequest.availableToSubCustomer) &&
        Objects.equals(this.exportConfigs, updateExportConfigGroupRequest.exportConfigs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, availableToSubCustomer, exportConfigs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateExportConfigGroupRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    availableToSubCustomer: ").append(toIndentedString(availableToSubCustomer)).append("\n");
    sb.append("    exportConfigs: ").append(toIndentedString(exportConfigs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

