/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * UpdateExportMessageFormats
 */
@JsonPropertyOrder({
  UpdateExportMessageFormats.JSON_PROPERTY_UPLINK,
  UpdateExportMessageFormats.JSON_PROPERTY_DOWNLINK,
  UpdateExportMessageFormats.JSON_PROPERTY_DOWNLINK_FAILED,
  UpdateExportMessageFormats.JSON_PROPERTY_JOIN_REQUEST,
  UpdateExportMessageFormats.JSON_PROPERTY_JOIN_ACCEPT
})
public class UpdateExportMessageFormats {
  public static final String JSON_PROPERTY_UPLINK = "uplink";
  private Boolean uplink;

  public static final String JSON_PROPERTY_DOWNLINK = "downlink";
  private Boolean downlink;

  public static final String JSON_PROPERTY_DOWNLINK_FAILED = "downlinkFailed";
  private Boolean downlinkFailed;

  public static final String JSON_PROPERTY_JOIN_REQUEST = "joinRequest";
  private Boolean joinRequest;

  public static final String JSON_PROPERTY_JOIN_ACCEPT = "joinAccept";
  private Boolean joinAccept;

  public UpdateExportMessageFormats() {
  }

  public UpdateExportMessageFormats uplink(Boolean uplink) {
    
    this.uplink = uplink;
    return this;
  }

   /**
   * Get uplink
   * @return uplink
  **/

  @JsonProperty(JSON_PROPERTY_UPLINK)

  public Boolean getUplink() {
    return uplink;
  }


  @JsonProperty(JSON_PROPERTY_UPLINK)
  public void setUplink(Boolean uplink) {
    this.uplink = uplink;
  }


  public UpdateExportMessageFormats downlink(Boolean downlink) {
    
    this.downlink = downlink;
    return this;
  }

   /**
   * Get downlink
   * @return downlink
  **/

  @JsonProperty(JSON_PROPERTY_DOWNLINK)

  public Boolean getDownlink() {
    return downlink;
  }


  @JsonProperty(JSON_PROPERTY_DOWNLINK)
  public void setDownlink(Boolean downlink) {
    this.downlink = downlink;
  }


  public UpdateExportMessageFormats downlinkFailed(Boolean downlinkFailed) {
    
    this.downlinkFailed = downlinkFailed;
    return this;
  }

   /**
   * Get downlinkFailed
   * @return downlinkFailed
  **/

  @JsonProperty(JSON_PROPERTY_DOWNLINK_FAILED)

  public Boolean getDownlinkFailed() {
    return downlinkFailed;
  }


  @JsonProperty(JSON_PROPERTY_DOWNLINK_FAILED)
  public void setDownlinkFailed(Boolean downlinkFailed) {
    this.downlinkFailed = downlinkFailed;
  }


  public UpdateExportMessageFormats joinRequest(Boolean joinRequest) {
    
    this.joinRequest = joinRequest;
    return this;
  }

   /**
   * Get joinRequest
   * @return joinRequest
  **/

  @JsonProperty(JSON_PROPERTY_JOIN_REQUEST)

  public Boolean getJoinRequest() {
    return joinRequest;
  }


  @JsonProperty(JSON_PROPERTY_JOIN_REQUEST)
  public void setJoinRequest(Boolean joinRequest) {
    this.joinRequest = joinRequest;
  }


  public UpdateExportMessageFormats joinAccept(Boolean joinAccept) {
    
    this.joinAccept = joinAccept;
    return this;
  }

   /**
   * Get joinAccept
   * @return joinAccept
  **/

  @JsonProperty(JSON_PROPERTY_JOIN_ACCEPT)

  public Boolean getJoinAccept() {
    return joinAccept;
  }


  @JsonProperty(JSON_PROPERTY_JOIN_ACCEPT)
  public void setJoinAccept(Boolean joinAccept) {
    this.joinAccept = joinAccept;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateExportMessageFormats updateExportMessageFormats = (UpdateExportMessageFormats) o;
    return Objects.equals(this.uplink, updateExportMessageFormats.uplink) &&
        Objects.equals(this.downlink, updateExportMessageFormats.downlink) &&
        Objects.equals(this.downlinkFailed, updateExportMessageFormats.downlinkFailed) &&
        Objects.equals(this.joinRequest, updateExportMessageFormats.joinRequest) &&
        Objects.equals(this.joinAccept, updateExportMessageFormats.joinAccept);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uplink, downlink, downlinkFailed, joinRequest, joinAccept);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateExportMessageFormats {\n");
    sb.append("    uplink: ").append(toIndentedString(uplink)).append("\n");
    sb.append("    downlink: ").append(toIndentedString(downlink)).append("\n");
    sb.append("    downlinkFailed: ").append(toIndentedString(downlinkFailed)).append("\n");
    sb.append("    joinRequest: ").append(toIndentedString(joinRequest)).append("\n");
    sb.append("    joinAccept: ").append(toIndentedString(joinAccept)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

