/*
 * netmore-web-backend
 * Front end for web services.
 *
 * The version of the OpenAPI document: 1.2.83
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lora.ns.netmore.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidNetworkServer
 */
@JsonPropertyOrder({
  ValidNetworkServer.JSON_PROPERTY_NETWORK_SERVER_ID,
  ValidNetworkServer.JSON_PROPERTY_NAME
})
public class ValidNetworkServer {
  public static final String JSON_PROPERTY_NETWORK_SERVER_ID = "networkServerId";
  private String networkServerId;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public ValidNetworkServer() {
  }

  public ValidNetworkServer networkServerId(String networkServerId) {
    
    this.networkServerId = networkServerId;
    return this;
  }

   /**
   * Get networkServerId
   * @return networkServerId
  **/

  @JsonProperty(JSON_PROPERTY_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNetworkServerId() {
    return networkServerId;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNetworkServerId(String networkServerId) {
    this.networkServerId = networkServerId;
  }


  public ValidNetworkServer name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidNetworkServer validNetworkServer = (ValidNetworkServer) o;
    return Objects.equals(this.networkServerId, validNetworkServer.networkServerId) &&
        Objects.equals(this.name, validNetworkServer.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkServerId, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidNetworkServer {\n");
    sb.append("    networkServerId: ").append(toIndentedString(networkServerId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

